#!/bin/env bash

set -e


remote_preset="https://github.com/almuhdilkarim/preset.git"
remote_proset="https://github.com/almuhdilkarim/proset.git"
remote_protos="https://github.com/almuhdilkarim/protos.git"