#!/bin/bash

set -e


## BOOT LOADERS
debuger=true
apppath="/var/lib/craine"
source "$apppath/striper"


## OPTIONS PROC
while getopts ":m:n:c:p" opt; do
    case $opt in
        m) mode="${OPTARG}"
        ;;
        n) name="${OPTARG}"
        ;;
        c) conf="${OPTARG}"
        ;;
        p) prof="${OPTARG}"
        ;;
    esac
done


if [[ $1 == "desktop" ]];then
    craine_desktop
elif [[ $1 == "guide" ]]; then
    craine_termine
elif [[ -z $mode ]]&&[[ ! -z $name ]];then
    craine_hackers $mode $name $conf $prof
else
    echo "Craine error: Mode not found"  
fi