#!/bin/bash

set -e



## TAKE OPTIONS
while getopts "o:n:b:m:a:l:p:" opt; do
    case $opt in
        o) proc="${OPTARG}"
        ;;
        n) craine_name="${OPTARG}"
        ;;
        b) craine_base="${OPTARG}"
        ;;
        m) craine_mode="${OPTARG}"
        ;;
        a) craine_auth="${OPTARG}"
        ;;
        l) craine_link="${OPTARG}"
        ;;
        p) craine_pitc="${OPTARG}"
        ;;
    esac
done


## CRAINE ENVI
craine_devs=true
craine_libs="/var/lib/craine" 
test -n $crdevs_stat && craine_libs=$(pwd)/library
source "$craine_libs/corest/loader"


## CRAINE MAIN
if [[ -n $proc ]];then
    if [[ $proc == "desktop" ]];then
        craine_guimode
    elif [[ $proc == "guides" ]];then
        craine_diamode
    elif [[ $proc == "tester" ]];then
        craine_testers
    elif [[ $proc == "proset" ]];then
        craine_proset $craine_mode
    elif [[ $proc == "preset" ]];then
        craine_preset $craine_mode
    elif [[ $proc == "protos" ]];then
        craine_protos $craine_mode
    elif [[ $proc == "editor" ]];then
        craine_editors
    elif [[ $proc == "create" ]];then
        craine_builder
    else
        notifer_error 'Operation parameter not found'
    fi
fi


unset craine_auth
unset craine_base
unset craine_name
unset craine_mode
unset craine_link
unset craine_pitc
unset craine_devs
unset craine_libs
