#!/bin/bash

set -e


## BOOT LOADERS
debuger=true
apppath="$(pwd)/library"
tespath="$(pwd)"
source "$apppath/striper"


## OPTIONS PROC
while getopts ":m:n:g:c:p" opt; do
    case $opt in
        m) mode="${OPTARG}"
        ;;
        n) name="${OPTARG}"
        ;;
        g) gitr="${OPTARG}"
        ;;
        c) conf="${OPTARG}"
        ;;
    esac
done


if [[ $mode == "desktop" ]];then
    craine_desktop
elif [[ $mode == "guide" ]]; then
    craine_termine
elif [[ $mode == "make" ]]&&[[ ! -z $name ]]; then
    craine_maker -n $name -g $gitr -c $conf -p $prof
elif [[ $mode == "edit" ]]&&[[ ! -z $name ]]; then
    craine_edito -n $name -g $gitr -f $file -p $prof
else
    echo "Craine error: Mode parameter not found"  
fi