#!/bin/env bash
# configuration data manipulation 
 
set -e


# eeplace value from configration file

function craine_config_rewrite () {

    local keyvar="${1}"
    local values='"'${2}'"'
    local config="${3}"

    if [[ $keyvar == "repo_sshd" ]]; then
        sed -i "s@^\(${keyvar}=\).*#\1${values}@" "$config"
    else
        sed -i "s@^\(${keyvar}=\).*@\1${values}@" "$config"
    fi
    
    unset keyvar
    unset values
    unset config
}



## CONFIG GETDATA
function craine_config_keyvar() {

    test -f $1 && grep -E '[a-zA-Z0-9_]*=' "$1" | grep -E -v '^#' | cut -d'=' -f1 | awk '{print $1}'
}

function craine_config_source() {
    
    test -f $1 && source "$1" 
}

function craine_config_editor() {
    test -f $1 && $EDITOR $1 
}