#!/bin/env bash
# autoload function

set -e



## SYSTEM

#-- declare core system remote sources
function craine_systems_remote() {

    remote_preset="https://github.com/almuhdilkarim/preset.git"
    remote_proset="https://github.com/almuhdilkarim/proset.git"
    remote_protos="https://github.com/almuhdilkarim/protos.git"
}


#-- craine core system directory structur
function craine_systems_struct() {
    
    craine_assets="$craine_libs/assets"
    craine_corest="$craine_libs/corest"
    craine_config="$craine_libs/config"
    craine_helper="$craine_libs/helper"
    craine_operat="$craine_libs/operat"
    craine_preset="$craine_libs/preset"
    craine_proset="$craine_libs/proset"
    craine_protos="$craine_libs/protos"
    craine_vendor="$craine_libs/vendor"
}


#-- craine core system assets
function craine_systems_assets() {

    craine_banner="$craine_assets/banner.txt"
    craine_brands="$craine_assets/brands.png"
}


#-- craine core system config
function craine_systems_config() {

    source "$craine_config/labrom"
    source "$craine_config/corest"
}


#-- craine core system library
function craine_systems_librar() {

    ## library
    source "$craine_helper/assets"
    source "$craine_helper/colors"
    source "$craine_helper/config"
    source "$craine_helper/cloner"
    source "$craine_helper/deploy"
    source "$craine_helper/logger"
    source "$craine_helper/seders"
    source "$craine_helper/secure"
}


#-- craine core system actions
function craine_systems_corest() {
    
    source "$craine_corest/create"
    source "$craine_corest/preset"
    source "$craine_corest/proset"
    source "$craine_corest/protos"
    source "$craine_corest/graphi"
}


#-- craine core system initialize
function craine_systems() {
    craine_systems_remote
    craine_systems_struct
    craine_systems_assets
    craine_systems_config
    craine_systems_librar
    craine_systems_corest
}




## MODULE

##-- load craine preset module and libary
function craine_modular_preset() {

    # load source
    source "$craine_preset/config"
} 


function craine_modular() {
    craine_modular_preset
}




## VENDOR

function craine_vendor_struct() {
    vendor_editor="$craine_vendor/editor"
}


function craine_vendor_prepar() {
    mkdir -p $craine_vendor
}


function craine_vendors() {
    craine_vendor_struct
    craine_vendor_prepar
}




## WORKER 

function craine_workers_struct() {

    worker_folder="$HOME/.local/craine"
    worker_secret="$HOME/.ssh/crainkey"
    worker_preset="$worker_folder/preset"
    worker_protos="$worker_folder/protos"
    worker_proset="$worker_folder/proset"
    worker_prolab="$worker_folder/prolab"
    worker_preloc="$worker_folder/preloc"
    worker_config="$worker_folder/config"
    worker_tokens="$worker_folder/tokens"
}


function craine_workers_prepar() {
    
    mkdir -p $worker_folder
    mkdir -p $worker_secret
    mkdir -p $worker_preset
    mkdir -p $worker_proset
    mkdir -p $worker_prolab
    mkdir -p $worker_preloc
    mkdir -p $worker_config
    mkdir -p $worker_tokens
}


function craine_workers_preset() {

    local locals_source="$worker_preset/default"

    if [[ ! -d $locals_source ]];then
        craine_remote_clones "$remote_preset" "$locals_source"
    fi

    unset locals_source
}


function craine_workers_proset() {

    local locals_source="$worker_preset/default"

    if [[ ! -d $locals_source ]];then
        craine_remote_clones "$remote_proset" "$locals_source"
    fi

    unset locals_source
}


function craine_workers_protos() {

    local locals_source="$worker_protos/default"

    if [[ ! -d $locals_source ]];then
        craine_remote_clones "$remote_protos" "$locals_source"
    fi

    unset locals_source
}


function craine_workers_secret() {
    mkdir -p $worker_secret
    chmod -R 700 $worker_secret
}


function craine_workers_tokens() {
    mkdir -p $worker_tokens/{preset,proset,protos} 
    chmod -R 700 $worker_tokens
}


function craine_workers_config() {
    cp -n $craine_config/worker $worker_config
}


function craine_workers() {
    craine_workers_struct
    craine_workers_prepar
    craine_workers_preset
    craine_workers_proset
    craine_workers_protos
    craine_workers_secret
    craine_workers_tokens
    craine_workers_config
}




# LIBRARY LOAD

craine_systems
craine_vendors
craine_modular
craine_workers





## PRESET CONFIGURE


## CRAINE DAEOMONIZ  
## craine_preset_basics &&
## craine_proset_basics &&
## craine_protos_basics &&
