#!/bin/env bash

set -e


## STRING MODIFIER
function craine_string_tovars() {
    
    local string=${1}
    local string=${string,,}                                  # string to lower
    local string=$( echo "${string}" | sed 's/ os//g' )       # remove os string
    local string=$( echo "${string}" | sed 's/ linux//g' )    # remove linux string
    local string=$( echo "${string}" | sed 's/ system//g' )   # remove system string
    local string="${string// /_}"                             # replace all spaces with underscore        
    local string="${string//-/_}"                             # replace all hyphens with underscore 
    echo ${string}
}


function craine_string_toslug() {
    
    local string=${1}
    local string=${string,,}                                  # string to lower
    local string=$( echo "${string}" | sed 's/ os//g' )       # remove os string
    local string=$( echo "${string}" | sed 's/ linux//g' )    # remove linux string
    local string=$( echo "${string}" | sed 's/ system//g' )   # remove system string
    local string="${string// /-}"                             # replace all spaces with hyphens        
    local string="${string//_/-}"                             # replace all underscore with hyphens
    echo ${string}
}


function craine_string_toname() {
    
    local string=${1}
    local string=$(echo "${string}" | sed -E 's/(^|\s+)([a-z])/\1\U\2/g')   # capitalize all first word
    local string="${string//-/ }"                                           # replace all hyphens with spaces         
    local string="${string//_/ }"                                           # replace all underscore with spaces
    echo ${string}
}


function craine_string_tolead() {
    
    local string=${1}
    local string="${string^^}"                                              # uppercase all character
    local string="${string//-/ }"                                           # replace all hyphens with spaces         
    local string="${string//_/ }"                                           # replace all underscore with spaces
    echo ${string}
}


function craine_string_random() {
    local random_number=$(( ( RANDOM % 900000 ) + 100000 ))
    echo $random_number
    unset random_number
}


## REPOSITORY PARSER

function craine_reposi_torepo() {

    local parser=${1}

    if [[ -n $( echo ${parser} | grep "https://" ) ]];then
        local parser=$(basename ${parser} )
    else
        local parser=$( echo ${parser} | sed 's|.*/||' )
    fi

    echo "$parser"
    unset parser
}


function craine_reposi_touser() {

    local parser=${1}

    if [[ -n $( echo ${parser} | grep "https://" ) ]];then
        local parser=$( basename "$(dirname "$parser")")
    else
        local parser=$( echo ${parser} | sed 's/.*:\([^/]*\)\/.*/\1/' )
    fi

    echo "$parser"
    unset parser
}


function craine_reposi_tohost() {

    local parser=${1}
    if [[ -n $( echo ${parser} | grep "https://" ) ]];then
        local parser=$( echo ${parser} | cut -d/ -f3)
    else
        local parser=$( echo ${parser} | sed -E 's/.*@([^:]*):.*/\1/' )
    fi
    
    echo "$parser"
    unset parser
}


function craine_reposi_topush() {

    local parser=${1} 
    local naming=$( craine_reposi_torepo $parser )
    local userer=$( craine_reposi_touser $parser )
    local hoster=$( craine_reposi_tohost $parser )
    local parser="https://${userer}:${repo_keys}@${hoster}/${userer}/${naming}"

    echo "$parser"
    unset parser
    unset naming
    unset userer
    unset hoster
}


function craine_reposi_tohttp() {
    
    local parser=${1}

    if [[ -n $( echo ${parser} | grep "https://" ) ]];then

        local parser=${1}

    else
        local naming=$( craine_reposi_torepo $parser )
        local userer=$( craine_reposi_touser $parser )
        local hoster=$( craine_reposi_tohost $parser )
        local parser="https://${hoster}/${userer}/${naming}"
    fi

   
    echo "$parser"
    unset parser
}


function craine_reposi_tosshd() {

    local parser=${1}

    if [[ -n $( echo ${parser} | grep "https://" ) ]];then
        local naming=$( craine_reposi_torepo $parser )
        local userer=$( craine_reposi_touser $parser )
        local hoster=$( craine_reposi_tohost $parser )
        local parser="git@${hoster}:${userer}/${naming}"
    else
        local parser=${1}
    fi

   
    echo "$parser"
    unset parser
}



## STRING REPLACING
function craine_retext_string() {
    echo "replace string on file"
}


function craine_retext_lining() {
    echo "replace line on file"
}


## STRING MANIPULATION
function craine_stringt_capit() {
    echo "string to capitalize"
}

function craine_stringt_upper() {
    echo "string to upper"
}

function craine_stringt_lower() {
    echo "string to lower"
}

function craine_stringt_uncor() {

    local strep="${1// /_}"     # replace all spaces with underscore        
    local strep="${strep//-/_}" # replace all hypens with underscore
    echo ${strep,,}
}

function craine_stringt_strip() {

    local strep="${1// /-}"     # replace all spaces with hyphens        
    local strep="${strep//_/-}" # replace all underscore with hyphens
    
    echo ${strep,,}

}

function craine_string_allcap() {
    echo "$1" | sed -E 's/(^|\s+)([a-z])/\1\U\2/g'
}

function craine_string_pather() {

    local strep=${1,,}                                     # string to lower
    local strep=$( echo "${strep}" | sed 's/os//g' )       # remove os string
    local strep=$( echo "${strep}" | sed 's/linux//g' )    # remove linux string
    local strep=$( echo "${strep}" | sed 's/system//g' )   # remove system string
    local strep="${strep//-/}"                             # replace all spaces with hyphens        
    local strep="${strep//_/}"                             # replace all underscore with hyphens
    echo ${strep}
    
}

function craine_string_unique() {
    echo "string to uniq"
}

function craine_string_varian() {
    echo "string to vars"
}

function craine_string_geturi() {
    echo "$1" | cut -d/ -f3
}

function craine_string_getlas() {
    basename "$1"
}

function craine_string_gettwo() {
    basename "$(dirname "$1")"
}




function craine_basename_path() {
    local dirname=$(basename $craine_link | sed 's/.git//g' )
    echo "$dirname"
}