#!/bin/env bash
# preset config writers
# 

set -e


## parsing distro name base on base name and spin name
function craine_preset_parser_rename() {

    local file=$1
    local name=$base_name
    

    if [[  $spin_name != "default" ]];then
        local name="$base_name $spin_name"
    fi
    

    craine_string_replace "OSNAME" "$name" "$file"

    unset name
    unset file
}


function craine_preset_parser_reslug() {

    local file=$1
    local name=$base_slug
    

    if [[ $option_spin != "default" ]];then
        local name="$base_slug-$spin_slug"
    fi

    craine_string_replace "OSSLUG" "$name" "$file"

    unset name
    unset file
}


function craine_preset_parser_relead() {

    local file=$1
    local name=$base_lead
    

    if [[  $option_spin != "default" ]];then
        local name="$base_lead $spin_lead"
    fi

    craine_string_replace "OSLEAD" "$name" "$file"

    unset name
    unset file
}


function craine_preset_parser_revars() {

    local file=$1
    local name=$base_vars
    

    if [[  $option_spin != "default" ]];then
        local name="$base_vars $spin_vars"
    fi

    craine_string_replace "OSVARS" "$name" "$file"

    unset name
    unset file
}


function craine_preset_parser_rebase() {

    local file=$1
    craine_preset_parser_rename $file
    craine_preset_parser_reslug $file
    craine_preset_parser_relead $file
    craine_preset_parser_revars $file 
    unset file

}


## register logging file for current preset action
function craine_preset_logger_create() {

    mkdir -p $logs_path && 

    echo  "                                                       " >> $logs_file
    echo  "#######################################################" >> $logs_file
    echo  " CRAINE PRESET  BUILD LOGS                             " >> $logs_file
    echo  "#######################################################" >> $logs_file
    echo  " distro   : $base_name                                 " >> $logs_file
    echo  " variant  : $spin_name                                 " >> $logs_file
    echo  " builder  : $USER                                      " >> $logs_file
    echo  " actions  : $action_mode                               " >> $logs_file
    echo  " modules  : $action_data                               " >> $logs_file
    echo  " starting : $( date )                                  " >> $logs_file
    echo  " hostname : $HOSTNAME                                  " >> $logs_file
    echo  "#######################################################" >> $logs_file
    echo  "                                                       " >> $logs_file
}


## add user input to envi for create preset action 
function craine_preset_parser_remake() {


    #--[1] root file
    local envi_file="$path_rand/crain"


    ### base variable
    craine_varkey_rewrite "base_name" "$base_name" "$envi_file"
    craine_varkey_rewrite "spin_name" "$spin_name" "$envi_file"
    craine_varkey_rewrite "auth_name" "$auth_name" "$envi_file"

    ## path variable
    craine_varkey_rewrite "path_main" "$rpat_main" "$envi_file"
    craine_varkey_rewrite "path_spin" "$rpat_spin" "$envi_file"

    ## site variable
    craine_varkey_rewrite "site_repo" "$repo_http" "$envi_file"



    #--[2] root file
    local read_file="$path_rand/README.md"
    craine_preset_parser_rebase $read_file &&



    #--[3] conf file
    local rels_file="$path_rand/conf/usr/lib/os-release" 
    craine_preset_parser_rebase $rels_file



    ## pure variable
    unset envi_file
    unset read_file
    unset rels_file
}
