#!/bin/env bash
# preset config writers

set -e



## add user input to envi for create preset action 
function craine_preset_config_prenvi() {


    local envi_file="$path_rand/envi"


    ### base variable
    craine_config_rewrite "base_name" "$base_name" $envi_file
    craine_config_rewrite "base_slug" "$base_slug" $envi_file
    craine_config_rewrite "base_lead" "$base_lead" $envi_file
    craine_config_rewrite "base_vars" "$base_vars" $envi_file


    ## spin variable
    craine_config_rewrite "spin_name" "$spin_name" $envi_file
    craine_config_rewrite "spin_slug" "$spin_slug" $envi_file
    craine_config_rewrite "spin_lead" "$spin_lead" $envi_file
    craine_config_rewrite "spin_vars" "$spin_vars" $envi_file


    ## author variable
    craine_config_rewrite "auth_name" "$auth_name" $envi_file
    craine_config_rewrite "auth_lead" "$auth_lead" $envi_file
    craine_config_rewrite "auth_slug" "$auth_slug" $envi_file
    craine_config_rewrite "auth_vars" "$auth_vars" $envi_file


    ## path variable
    craine_config_rewrite "path_main" "$rpat_main" $envi_file
    craine_config_rewrite "path_spin" "$rpat_spin" $envi_file


    ## repo variable
    test -n $repo_host && craine_config_rewrite "repo_host" "$repo_host" "$envi_file"
    test -n $repo_user && craine_config_rewrite "repo_user" "$repo_user" "$envi_file"
    test -n $repo_name && craine_config_rewrite "repo_name" "$repo_name" "$envi_file"
    test -n $repo_http && craine_config_rewrite "repo_http" "$repo_http" "$envi_file"
    test -n $repo_sshd && craine_config_rewrite "repo_sshd" "$repo_sshd" "$envi_file"
    test -n $rrep_toke && craine_config_rewrite "repo_toke" "$rrep_toke" "$envi_file"
    test -n $rrep_keys && craine_config_rewrite "repo_keys" "$rrep_keys" "$envi_file"


    ## pure variable
    unset envi_file
}