#!/bin/env bash
## craine update




#######################################
##---| 1  DATUMS
#######################################

# 1 | source module metadata

function craine_update_datums_pool () {
   

    ## logic variable
    option_spin=$( [[ -z $option_spin ]] && echo "default" || echo "$option_spin" )


    ## loads configs
    local base_conf="$worker_folder/$action_data/$option_name/$option_spin/crain"
    

    if [[ ! -f $base_conf ]];then
        craine_nolog "A58001"
    else
        source $base_conf
    fi

    ## loads datum
    base_name=$base_name
    spin_name=$spin_name
    auth_name=$auth_name
    rand_name=$( craine_string_torand )
    time_name=$( craine_string_totime )


    ## base variable
    base_name=$( craine_module_toname ${base_name} )
    base_slug=$( craine_module_toslug ${base_name} )
    base_lead=$( craine_module_tolead ${base_name} )
    base_vars=$( craine_module_tovars ${base_name} )
    


    ## spin variabel
    spin_name=$( craine_module_toname ${spin_name} )
    spin_slug=$( craine_module_toslug ${spin_name} )
    spin_lead=$( craine_module_tolead ${spin_name} )
    spin_vars=$( craine_module_tovars ${spin_name} )
    


    ## author variable
    auth_name=$( craine_module_toname "$auth_name" )    
    auth_lead=$( craine_module_toslug "$auth_name" )    
    auth_slug=$( craine_module_tolead "$auth_name" )    
    auth_vars=$( craine_module_tovars "$auth_name" ) 



    ## locals variable
    vars_rand=$( craine_module_filetim )
    path_base="$worker_folder/$action_data"
    path_main="$path_base/$base_slug"                                       # distros folders
    path_rand="$path_main/$vars_rand"                                       # temporary paths
    path_spin="$path_main/$spin_slug"                                       # variant folders
    


    ## remote variable
    repo_toke="$worker_folder/tokens/$action_data/$base_slug/$spin_slug"    # repository apts
    repo_host=$( craine_remote_tohost $site_repo )                          # repository host
    repo_user=$( craine_remote_touser $site_repo )                          # repository user
    repo_name=$( craine_remote_torepo $site_repo )                          # repository name
    repo_http=$( craine_remote_tohttp $site_repo )                          # repository link
    repo_sshd=$( craine_remote_tosshd $site_repo )                          # repository name
    repo_push=$( craine_remote_topush $site_repo )                          # repository push
    repo_keys="$worker_secret/master"                                       # repository sshd



    ## loging variable                                       
    logs_file="$worker_logger/$action_mode-$action_data-$vars_rand"         # logging filedat
    logs_pack="$path_spin/track/$vars_rand"
    logs_make="$path_spin/track/_init"



    ## tokens variable
    toke_path="$repo_toke/repo"                                                             # tokneizers path
    toke_data=$( cat $toke_path )                                                           # tokneizers data
    toke_uris="https://${repo_user}:${toke_data}@${repo_host}/${repo_user}/${repo_name}"


    ## notife variable
    stage_num=1
    alert_num=1
    erorr_num=1

    craine_nolog "I58001"
}

function craine_update_datum_proc () {
    echo debug
}


function craine_update_datum_pure () {
    echo debug
}


#######################################
##--- LIBRARY
#######################################


##--[1] validate sssh secret
function craine_update_remote_keys () {


    #--[1] initialzer ssh-agents
    if [[ ! -f $worker_secret/master  ]];then    
        return
    fi


    #--[2] initialzer ssh-agents 
    eval "$(ssh-agent -s)" > /dev/null 2>&1 &&
    
    craine_prelo $? I52001 E52001


    #--[3] add secret to ssh agent 
    ssh-add $worker_secret/master > /dev/null 2>&1

    craine_prelo $? I52001 E52001


    #--[4] connection test to github
    yes | ssh -T git@github.com >  /dev/null 2>&1

    craine_prelo $? I52001 E52001


    #--[5] validate ssh connection
    cd $path_spin && git ls-remote --exit-code $repo_sshd > /dev/null 2>&1
    
    if [[ $? -eq 0 ]]; then
        craine_update_notlog 1 1101 && 
        sshd_stat=true 
    else
        craine_update_notlog 3 1101
    fi
}


##--[2] validate access tokens
function craine_update_remote_toke () {


    #--[1] validate ssh connection, return false is ssh connection available
    if [[ $sshd_stat == true ]];then
        return
    fi


    #--[2] check personal access tokens available, exit with error code if not exist
    if [[ -z toke_data ]];then
        echo "no remote resources available" && exit 1
    fi


    #--[3] validate uri connection
    cd $path_spin && git remote set-url origin "$toke_uris"

    craine_prelo $? I52001 E52001
    

    #--[4] validate uri connection
    test -z $http_keys && cd $path_spin &&  git ls-remote --exit-code $repo_http > /dev/null 2>&1



    #--[5] validate uri connection
    if [[ $? -ne 0 ]]; then

        #--[5-1] validate uri connection
        cd $path_spin && git remote set-url origin "$site_repo"

        craine_update_notlog 3 1101

        #--[5-2] validate uri connection
        echo "no remote resources available" && exit 1
    else
        craine_update_notlog 1 1101
    fi


    #--[6] validate uri connection
    http_stat=true 


    #--[7] validate uri connection
    cd $path_spin && git remote set-url origin "$site_repo"

    craine_prelo $? I52001 E52001
}


##--(3) update version | major
function craine_update_remote_majo () {


    #--[1] root file
    if [[ -z $sshd_stat  ]]&&[[ -z $http_stat ]];then
        return
    fi


    #--[1] root file
    local envi_file="$path_spin/crain"


    #--[1] root file
    ver_major=$((ver_major + 1 ))


    #--[1] root file
    sed -i "s@^\(ver_major=\).*@\1${ver_major}@" "$envi_file"
    craine_prelo $? I52001 E52001

}


##--(3) update version | minor
function craine_update_remote_mino () {

    
    #--[1] root file
    if [[ -z $sshd_stat  ]]&&[[ -z $http_stat ]];then
        return
    fi


    #--[1] root file
    local envi_file="$path_spin/crain"


    #--[1] root file
    ver_minor=$((ver_minor + 1 ))


    #--[1] root file
    sed -i "s@^\(ver_minor=\).*@\1${ver_minor}@" "$envi_file"

    craine_prelo $? I52001 E52001
}


##--(3) update version | pathc
function craine_update_remote_patc () {


    #--[1] root file
    if [[ -z $sshd_stat  ]]&&[[ -z $http_stat ]];then
        return
    fi


    #--[1] root file
    local envi_file="$path_spin/crain"


    #--[1] root file
    ver_patch=$((ver_patch + 1 ))


    #--[1] root file
    sed -i "s@^\(ver_patch=\).*@\1${ver_patch}@" "$envi_file"
    
    craine_prelo $? I52001 E52001
}


##--[4] populate and commit
function craine_update_remote_pool () {


    #--[1] validate uri connection
    cd $path_spin && git add . > /dev/null 2>&1 &&

    craine_prelo $? I52001 E52001


    #--[2] validate uri connection
    echo -e  "\t${green}   [ Press enter for autocommit message ]    ${reset}" | sed 's/^[[:space:]]*//' && 
    echo -ne "\t${green}   |--> Insert commit message : ${reset}" | sed 's/^[[:space:]]*//' &&  read commit


    #--[3] automatic commit message
    if [[ -z $commit ]];then
        commit="update version $ver_major.$ver_minor.$ver_patch at $(date '+%A %W %Y %X')"
    fi


    #--[4] commit message updating
    cd $path_spin && git commit -m "$commit" > /dev/null 2>&1

    craine_prelo $? I52001 E52001
}


##--[5] push to remote host
function craine_update_remote_push () {

    #--[1] pushed using sshd connection
    if [[ $shhd_stat == true  ]]; then

        #--[1.1] pushed using sshd connection
        cd $path_spin && git push > /dev/null 2>&1 &&
        craine_prelo $? I52001 E52001


        #--[1.2] pushed using sshd connection
        return
    fi


    #--[2] pushed using http connection
    if [[ $http_stat == true  ]]; then

        #--[2.1] pushed using sshd connection
        cd $path_spin && git remote set-url origin "$toke_uris"
        craine_prelo $? I52001 E52001


        #--[2.2] pushed using sshd connection
        cd $path_spin && git push > /dev/null 2>&1 &&
        craine_prelo $? I52001 E52001


        #--[2.3] pushed using sshd connection
        cd $path_spin && git remote set-url origin "$site_repo"
        craine_prelo $? I52001 E52001
    fi   
}


#######################################
##--- PROGRESS
#######################################


##--[5] update as major version
function craine_update_verses_majo () {

    #--[1] populate preset data
    craine_update_datums_pool


    #--[2] validate preset keys
    craine_update_remote_secr


    #--[3] validate preset toke
    craine_update_remote_toke


    #--[4] update patch numbers
    craine_update_remote_majo


    #--[5] defined commit texts
    craine_update_remote_pool


    #--[6] updates repositories
    craine_update_remote_push
}


##--[5] update as minor version
function craine_update_verses_mino () {

    #--[1] populate preset data
    craine_update_datums_pool


    #--[2] validate preset keys
    craine_update_remote_secr


    #--[3] validate preset toke
    craine_update_remote_toke


    #--[4] update patch numbers
    craine_update_remote_mino


    #--[5] defined commit texts
    craine_update_remote_pool


    #--[6] updates repositories
    craine_update_remote_push
}


##--[5] update for patching bug
function craine_update_verses_bufi () {


    #--[1] populate preset data
    craine_update_datums_pool


    #--[2] validate preset keys
    craine_update_remote_keys


    #--[3] validate preset toke
    craine_update_remote_toke


    #--[4] update patch numbers
    craine_update_remote_patc


    #--[5] defined commit texts
    craine_update_remote_pool


    #--[6] updates repositories
    craine_update_remote_push
}



#######################################
##--- PRESET
#######################################


function craine_update_preset () {

    if [[ $option_mode == "minor" ]]; then

        craine_update_verses_mino

    elif [[ $option_mode == "major" ]]; then

        craine_update_verses_majo

    else

        craine_update_verses_bufi
    fi
}



#######################################
##--- PROSET
#######################################


function craine_update_proset() {
    echo debug
}


#######################################
##--- PROTOS
#######################################


function craine_update_protos() {
    echo debug
}



#######################################
##--- INITIAL
#######################################


function craine_update() {


    test -z $action_data && craine_update_notlog 4 1


    if [[ $action_data == "preset" ]]; then
        unset crain_data && craine_update_preset && exit 0
    fi


    if [[ $action_data == "proset" ]]; then
        unset crain_data && craine_update_proset && exit 0
    fi


    if [[ $action_data == "protos" ]]; then
        unset crain_data && craine_update_protos && exit 0
    fi


    if [[ $action_data == "release" ]]; then
        unset crain_data && craine_update_images && exit 0
    fi


    if [[ $action_data == "testing" ]]; then
        unset crain_data && craine_update_tester && exit 0
    fi
}