#!/bin/env bash
## craine update




#######################################
##---| 1  DATUMS
#######################################


# 1 | source module metadata
function craine_update_datums_pool () {
   

    ## logic variable
    option_spin=$( [[ -z $option_spin ]] && echo "default" || echo "$option_spin" )


    ## loads configs
    base_conf="$worker_folder/$action_data/$option_name/$option_spin/crain"
    

    if [[ ! -f $base_conf ]];then
        craine_nolog "A59001"
    else
        source $base_conf
    fi


    ## loads datum
    base_name=$base_name
    spin_name=$spin_name
    auth_name=$auth_name


    ## rands datum
    rand_name=$( craine_string_torand )
    time_name=$( craine_string_totime )


    ## sites dataum
    site_repo=$site_repo


    ## noog variable
    stage_num=1
    alert_num=0
    erorr_num=0

    craine_nolog "I59001"
}


function craine_update_datum_proc () {


    ## base variable
    base_name=$( craine_module_toname ${base_name} )
    base_slug=$( craine_module_toslug ${base_name} )
    
    
    ## spin variabel
    spin_name=$( craine_module_toname ${spin_name} )
    spin_slug=$( craine_module_toslug ${spin_name} )

    
    ## path variable                                    
    path_spin="$worker_folder/$action_data/$base_slug/$spin_slug"                           # distros folders                                             # variant folders
    

    ## repo variable
    repo_keys=$( cat $worker_folder/tokens/$action_data/$base_slug/$spin_slug/repo )        # repository tokenizer  
    repo_http=$( craine_remote_tohttp $site_repo )                                          # repository http link              
    repo_sshd=$( craine_remote_tosshd $site_repo )                                          # repository sshd link
    repo_push=$( craine_remote_topush $site_repo )                                          # repository push link
  

    ## logs variable                                       
    logs_core="$worker_logger/$action_mode-$action_data-$time_name"         # logging filedat
    logs_pack="$path_spin/track/$time_name"


    craine_nolog "I59002"
}


function craine_update_datum_pure () {

    unset base_conf
    unset base_name
    unset base_slug
    unset spin_name
    unset spin_slug
    unset path_spin
    unset repo_keys
    unset repo_http
    unset repo_sshd
    unset repo_push
    unset logs_core
    unset logs_pack
    unset stage_num
    unset alert_num
    unset erorr_num
    unset comit_msg
}




#######################################
##--- LIBRARY
#######################################



##--[1] validate sssh secret
function craine_update_remote_dial () {

    craine_dialog_option_text "Insert Commit Message : [ PRESS ENTER for Autocommit ]" comit_msg
}

##--[1] validate sssh secret
function craine_update_remote_keys () {


    #--[1] initialzer ssh-agents
    if [[ ! -f $worker_secret/master  ]];then    
        craine_nolog W59001 && return
    fi


    #--[2] initialzer ssh-agents 
    eval "$(ssh-agent -s)" > /dev/null 2>&1 &&
    
    craine_prelo $? I59003 W59002


    #--[3] add secret to ssh agent 
    ssh-add $worker_secret/master > /dev/null 2>&1

    craine_prelo $? I59004 W59002


    #--[4] connection test to github
    yes | ssh -T git@github.com >  /dev/null 2>&1

    craine_prelo $? I59005 W59003


    #--[5] validate ssh connection
    cd $path_spin && git ls-remote --exit-code $repo_sshd > /dev/null 2>&1
    
    if [[ $? -eq 0 ]]; then
        craine_nolog I59006 && 
        sshd_stat=true 
    else
        craine_nolog W59004
    fi
}


##--[2] validate access tokens
function craine_update_remote_toke () {


    #--[1] validate ssh connection, return false is ssh connection available
    if [[ $sshd_stat == true ]];then
        craine_nolog I59007 && 
        return
    fi


    #--[2] check personal access tokens available, exit with error code if not exist
    if [[ -z repo_keys ]];then
        ecraine_nolog A59002
    fi


    #--[3] setup custom uri models
    test -n $repo_push && cd $path_spin && git remote set-url origin "$repo_push"

    craine_prelo $? I59008 W59005
    

    #--[4] validate uri connection
    test -n $repo_push && cd $path_spin &&  git ls-remote --exit-code $repo_push > /dev/null 2>&1

    craine_prelo $? I59008 A59003


    #--[5] set http for push operation
    http_stat=true 
    

    #--[6] validate uri connection
    cd $path_spin && git remote set-url origin "$site_repo"

    craine_nolog I59009
}


##--(3) update version | major
function craine_update_remote_majo () {


    #--[1] root file
    if [[ -z $sshd_stat  ]]&&[[ -z $http_stat ]];then
        return
    fi


    #--[1] root file
    local envi_file="$path_spin/crain"


    #--[1] root file
    ver_major=$((ver_major + 1 ))


    #--[1] root file
    sed -i "s@^\(ver_major=\).*@\1${ver_major}@" "$envi_file"
    craine_prelo $? I59001 W59001

}


##--(3) update version | minor
function craine_update_remote_mino () {

    
    #--[1] root file
    if [[ -z $sshd_stat  ]]&&[[ -z $http_stat ]];then
        return
    fi


    #--[1] root file
    local envi_file="$path_spin/crain"


    #--[1] root file
    ver_minor=$((ver_minor + 1 ))


    #--[1] root file
    sed -i "s@^\(ver_minor=\).*@\1${ver_minor}@" "$envi_file"

    craine_prelo $? I59001 W59001
}


##--(3) update version | pathc
function craine_update_remote_patc () {


    #--[1] root file
    if [[ -z $sshd_stat  ]]&&[[ -z $http_stat ]];then
        ecraine_nolog A59004
    fi


    #--[1] root file
    local envi_file="$path_spin/crain"


    #--[1] root file
    ver_patch=$((ver_patch + 1 ))


    #--[1] root file
    sed -i "s@^\(ver_patch=\).*@\1${ver_patch}@" "$envi_file"
    
    craine_prelo $? I59012 W59005
}


##--[4] populate and commit
function craine_update_remote_pool () {


    #--[1] validate uri connection
    cd $path_spin && git add . > /dev/null 2>&1 &&

    craine_prelo $? I59013 W59006


    #--[3] automatic commit message
    if [[ -z $comit_msg ]];then
        comit_msg="update version $ver_major.$ver_minor.$ver_patch at $(date '+%A %W %Y %X')"
    fi


    #--[4] commit message updating
    cd $path_spin && git commit -m "$comit_msg" > /dev/null 2>&1

    craine_prelo $? I59014 E59001
}


##--[5] push to remote host
function craine_update_remote_push () {

    #--[1] pushed using sshd connection
    if [[ $shhd_stat == true  ]]; then

        #--[1.1] pushed using sshd connection
        cd $path_spin && git push > /dev/null 2>&1 &&

        craine_prelo $? I59015 E59002


        #--[1.2] pushed using sshd connection
        return
    fi


    #--[2] pushed using http connection
    if [[ $http_stat == true  ]]; then

        #--[2.1] pushed using sshd connection
        cd $path_spin && git remote set-url origin "$repo_push"


        #--[2.2] pushed using sshd connection
        cd $path_spin && git push > /dev/null 2>&1 &&
        craine_prelo $? I59015 E59002


        #--[2.3] pushed using sshd connection
        cd $path_spin && git remote set-url origin "$site_repo"
    fi   
}




#######################################
##--- PROGRESS
#######################################


##--[5] update as major version
function craine_update_verses_majo () {


    #--[1] populate preset data
    craine_update_datums_pool


    #--[1] adjusted preset data
    craine_update_datum_proc


    #--[2] validate preset keys
    craine_update_remote_secr


    #--[3] validate preset toke
    craine_update_remote_toke


    #--[4] update patch numbers
    craine_update_remote_majo


    #--[5] defined commit texts
    craine_update_remote_pool


    #--[6] updates repositories
    craine_update_remote_push

    
    #--[7] purify data variable
    craine_update_datum_pure
}


##--[5] update as minor version
function craine_update_verses_mino () {

    #--[1] populate preset data
    craine_update_datums_pool


    #--[1] adjusted preset data
    craine_update_datum_proc


    #--[2] validate preset keys
    craine_update_remote_secr


    #--[3] validate preset toke
    craine_update_remote_toke


    #--[4] update patch numbers
    craine_update_remote_mino


    #--[5] defined commit texts
    craine_update_remote_pool


    #--[6] updates repositories
    craine_update_remote_push

    
    #--[7] purify data variable
    craine_update_datum_pure
}


##--[5] update for patching bug
function craine_update_verses_bufi () {

    craine_banner_render_head

    #--[1] making commit message
    craine_update_remote_dial


    #--[2] populate preset data
    craine_update_datums_pool

    
    #--[3] adjusted preset data
    craine_update_datum_proc


    #--[4] validate preset keys
    craine_update_remote_keys


    #--[5] validate preset toke
    craine_update_remote_toke


    #--[6] update patch numbers
    craine_update_remote_patc


    #--[7] defined commit texts
    craine_update_remote_pool


    #--[8] updates repositories
    craine_update_remote_push


    #--[9] show process status
    craine_report_status_info


    #--[10] purify data variable
    craine_update_datum_pure

    
}



#######################################
##--- PRESET
#######################################


function craine_update_preset () {

    if [[ $option_mode == "minor" ]]; then

        craine_update_verses_mino

    elif [[ $option_mode == "major" ]]; then

        craine_update_verses_majo

    else

        craine_update_verses_bufi
    fi
}



#######################################
##--- PROSET
#######################################


function craine_update_proset() {
    echo debug
}


#######################################
##--- PROTOS
#######################################


function craine_update_protos() {
    echo debug
}



#######################################
##--- INITIAL
#######################################


function craine_update() {


    test -z $action_data && craine_update_notlog 4 1


    if [[ $action_data == "preset" ]]; then
        unset crain_data && craine_update_preset && exit 0
    fi


    if [[ $action_data == "proset" ]]; then
        unset crain_data && craine_update_proset && exit 0
    fi


    if [[ $action_data == "protos" ]]; then
        unset crain_data && craine_update_protos && exit 0
    fi


    if [[ $action_data == "release" ]]; then
        unset crain_data && craine_update_images && exit 0
    fi


    if [[ $action_data == "testing" ]]; then
        unset crain_data && craine_update_tester && exit 0
    fi
}