#!/bin/env bash
## craine update




#######################################
##---| 1  DATUMS
#######################################


#--| source module metadata
function craine_update_datums_pool () {
   

    ## logic variable
    option_spin=$( [[ -z $option_spin ]] && echo "default" || echo "$option_spin" )


    ## loads configs
    base_conf="$worker_folder/$action_data/$option_name/$option_spin/crain"
    

    if [[ ! -f $base_conf ]];then
        craine_nolog "A59001"
    else
        source $base_conf
    fi


    ## loads datum
    base_name=$base_name
    spin_name=$spin_name
    auth_name=$auth_name


    ## rands datum
    rand_name=$( craine_string_torand )
    time_name=$( craine_string_totime )


    ## sites dataum
    site_repo=$site_repo


    ## noog variable
    stage_num=1
    alert_num=0
    erorr_num=0

}


#--| parsing for declare vars
function craine_update_datums_proc () {


    ## base variable
    base_name=$( craine_module_toname ${base_name} )
    base_slug=$( craine_module_toslug ${base_name} )
    
    
    ## spin variabel
    spin_name=$( craine_module_toname ${spin_name} )
    spin_slug=$( craine_module_toslug ${spin_name} )

    
    ## path variable                                    
    path_spin="$worker_folder/$action_data/$base_slug/$spin_slug"                           # distros folders                                             # variant folders
    

    ## repo variable
    repo_keys=$( cat $worker_folder/tokens/$action_data/$base_slug/$spin_slug/repo )        # repository tokenizer  
    repo_http=$( craine_remote_tohttp $site_repo )                                          # repository http link              
    repo_sshd=$( craine_remote_tosshd $site_repo )                                          # repository sshd link
    repo_push=$( craine_remote_topush $site_repo )                                          # repository push link
    repo_bran=main
  

    ## versioning
    alpa_vers=$path_spin/.git/alpa-version
    beta_vers=$path_spin/.git/beta-version
    devs_vers=$path_spin/.git/devs-version
    main_vers=$path_spin/.git/main-version


    ## logs variable                                       
    logs_core="$worker_logger/$action_mode-$action_data-$time_name"         # logging filedat
    logs_pack="$path_spin/.git/track/$time_name"
}


#--| delete unused metavars
function craine_update_datums_pure () {

    unset base_conf
    unset base_name
    unset base_slug
    unset spin_name
    unset spin_slug
    unset path_spin
    unset repo_keys
    unset repo_http
    unset repo_sshd
    unset repo_push
    unset logs_core
    unset logs_pack
    unset stage_num
    unset alert_num
    unset erorr_num
    unset comit_msg
    unset branc_msg
    unset alpa_vers
    unset beta_vers
    unset devs_vers
    unset main_vers
    unset repo_vers  
    unset repo_bran
}




#######################################
##---| 2 LIBRARY
#######################################


##--| prepare update extra data file 
function craine_update_remote_prep () {

    if [[ ! -f $alpa_vers ]];then
        echo "ver_major=0" >  $alpa_vers 
        echo "ver_minor=0" >> $alpa_vers
        echo "ver_patch=0" >> $alpa_vers
    fi

    if [[ ! -f $beta_vers ]];then
        echo "ver_major=0" >  $beta_vers 
        echo "ver_minor=0" >> $beta_vers
        echo "ver_patch=0" >> $beta_vers
    fi

    if [[ ! -f $devs_vers ]];then
        echo "ver_major=0" >  $devs_vers 
        echo "ver_minor=0" >> $devs_vers
        echo "ver_patch=0" >> $devs_vers
    fi

    if [[ ! -f $main_vers ]];then
        echo "ver_major=0" >  $main_vers 
        echo "ver_minor=0" >> $main_vers
        echo "ver_patch=0" >> $main_vers
    fi


    #--[3] create logger folder
    mkdir -p $path_spin/.git/track/

    #--[3] populate logger data
    craine_banner_render_logs
}


##--| slect branch version file
function craine_update_remote_vers () {


    ## source alpha version metadata
    if [[ $branc_msg == 3 ]];then
        repo_vers=$alpa_vers
    fi


    ## source beta version metadata
    if [[ $branc_msg == 2 ]];then
        repo_vers=$beta_vers
        
    fi


    ## source devel version metadata
    if [[ $branc_msg == "4" ]];then
        repo_vers=$devs_vers
    fi


    ## source main version metadata
    if [[ $branc_msg != "2" ]]&&[[ $branc_msg != "3" ]]&&[[ $branc_msg != "4" ]];then
        repo_vers=$main_vers
    fi


    ## validate source not empty
    if [[ -z $repo_vers  ]]; then
        echo "versioning error" &&  exit 
    fi


    ## get source
    source $repo_vers
}


##--| render user option dialog
function craine_update_remote_dial () {

    #--[1] branch options dialog
    local text="Choose current active branch for this action"
    local list=( main beta alpha devel )
    craine_dialog_option_list "$text" branc_msg
    
    
    #--[2] commit message dialog
    local text="Insert Commit Message : [ PRESS ENTER for Autocommit ]"
    craine_dialog_option_text "$text" comit_msg
}


##--| validate file changes
function craine_update_remote_null () {

    if git diff-index --quiet HEAD --; then
        echo "reposiotry is update" && exit 0
    fi
}


##--| validate sssh secret
function craine_update_remote_keys () {


    #--[1] initialzer ssh-agents
    if [[ ! -f $worker_secret/master  ]];then    
        craine_nolog W59001 && return
    fi


    #--[2] initialzer ssh-agents 
    eval "$(ssh-agent -s)" > /dev/null 2>&1 &&
    
    craine_prelo $? I59003 W59002


    #--[3] add secret to ssh agent 
    ssh-add $worker_secret/master > /dev/null 2>&1

    craine_prelo $? I59004 W59002


    #--[4] connection test to github
    yes | ssh -T git@github.com >  /dev/null 2>&1

    craine_prelo $? I59005 W59003


    #--[5] validate ssh connection
    cd $path_spin && git ls-remote --exit-code $repo_sshd > /dev/null 2>&1
    
    if [[ $? -eq 0 ]]; then
        craine_nolog I59006 && 
        sshd_stat=true 
    else
        craine_nolog W59004
    fi
}


##--| validate access tokens
function craine_update_remote_toke () {


    #--[1] validate ssh connection, return false is ssh connection available
    if [[ $sshd_stat == true ]];then
        craine_nolog I59007 && 
        return
    fi


    #--[2] check personal access tokens available, exit with error code if not exist
    if [[ -z repo_keys ]];then
        ecraine_nolog A59002
    fi


    #--[3] setup custom uri models
    test -n $repo_push && cd $path_spin && git remote set-url origin "$repo_push"

    craine_prelo $? I59008 W59005
    

    #--[4] validate uri connection
    test -n $repo_push && cd $path_spin &&  git ls-remote --exit-code $repo_push > /dev/null 2>&1

    craine_prelo $? I59008 A59003


    #--[5] set http for push operation
    http_stat=true 
    

    #--[6] validate uri connection
    cd $path_spin && git remote set-url origin "$site_repo"

    craine_nolog I59009
}


##--| update version | major
function craine_update_remote_majo () {


    if [[ $option_mode != "major" ]]; then
        return
    fi

    #--[1] root file
    if [[ -z $sshd_stat  ]]&&[[ -z $http_stat ]];then
        return
    fi


    #--[1] root file
    ver_patch=0
    ver_minor=0
    ver_major=$((ver_major + 1 ))


    #--[1] root file
    sed -i "s@^\(ver_patch=\).*@\1${ver_patch}@" "$repo_vers"
    sed -i "s@^\(ver_minor=\).*@\1${ver_minor}@" "$repo_vers"
    sed -i "s@^\(ver_major=\).*@\1${ver_major}@" "$repo_vers"
    
    craine_prelo $? I59001 W59001
}


##--| update version | minor
function craine_update_remote_mino () {

    
    if [[ $option_mode != "minor" ]]; then
        return
    fi

    #--[1] root file
    if [[ -z $sshd_stat  ]]&&[[ -z $http_stat ]];then
        return
    fi


    #--[1] root file
    ver_patch=0
    ver_minor=$((ver_minor + 1 ))


    #--[1] root file
    sed -i "s@^\(ver_minor=\).*@\1${ver_minor}@" "$repo_vers"
    sed -i "s@^\(ver_patch=\).*@\1${ver_patch}@" "$repo_vers"

    craine_prelo $? I59001 W59001
}


##--| update version | patch
function craine_update_remote_bufi () {


    if [[ $option_mode == "minor" ]]||[[ $option_mode == "major" ]]; then
        return
    fi


    #--[1] root file
    if [[ -z $sshd_stat  ]]&&[[ -z $http_stat ]];then
        ecraine_nolog A59004
    fi



    #--[1] root file
    local envi_file="$path_spin/crain"


    #--[1] root file
    ver_patch=$((ver_patch + 1 ))


    #--[1] root file
    sed -i "s@^\(ver_patch=\).*@\1${ver_patch}@" "$repo_vers"
    
    craine_prelo $? I59012 W59005
}


##--| checkout branch | alpha 
function craine_update_remote_alpa () {

    if [[ $branc_msg != 3 ]];then
        return
    fi

    local bran_stat=$(git rev-parse --verify --quiet "alpha" )

    if [[ -n $stat ]]; then
        cd $path_spin && git switch alpha > /dev/null 2>&1
    else
        cd $path_spin && git switch -c alpha > /dev/null 2>&1
    fi

    repo_bran=alpha
    unset bran_stat
}


##--| checkout branch | beta
function craine_update_remote_beta () {

    if [[ $branc_msg != "2" ]];then
        return
    fi

    local bran_stat=$(git rev-parse --verify --quiet "beta" )

    if [[ -n $stat ]]; then
        cd $path_spin && git switch beta > /dev/null 2>&1
    else
        cd $path_spin && git switch -c beta > /dev/null 2>&1
    fi

    repo_bran=beta
    unset bran_stat
}


##--| checkout branch | devel
function craine_update_remote_devs () {

    if [[ $branc_msg != "4" ]];then
        return
    fi

    local bran_stat=$(git rev-parse --verify --quiet "devel" )

    if [[ -n $stat ]]; then
        cd $path_spin && git switch devel > /dev/null 2>&1
    else
        cd $path_spin && git switch -c devel > /dev/null 2>&1
    fi

    repo_bran=devel
    unset bran_stat
}


##--| checkout branch | main
function craine_update_remote_main () {

    if [[ $branc_msg == "2" ]]||[[ $branc_msg == "3" ]]||[[ $branc_msg == "4" ]];then
        return
    fi

    local bran_stat=$(git rev-parse --verify --quiet "main" )

    if [[ -n $stat ]]; then
        cd $path_spin && git switch -q main > /dev/null 2>&1
    else
        cd $path_spin && git switch -c -q main > /dev/null 2>&1
     
    fi
    
    repo_bran=main
    unset bran_stat
}


##--| populate and local commit
function craine_update_remote_pool () {


    #--[0] update log to remote
    craine_loger_clone


    #--[1] validate uri connection
    cd $path_spin && git add . > /dev/null 2>&1 &&

    craine_prelo $? I59013 W59006


    #--[3] automatic commit message
    if [[ -z $comit_msg ]];then
        comit_msg="update version $ver_major.$ver_minor.$ver_patch at $(date '+%A %W %Y %X')"
    fi


    #--[4] commit message updating
    cd $path_spin && git commit -m "$comit_msg" > /dev/null 2>&1

    craine_prelo $? I59014 E59001
}


##--| push to remote host | sshd
function craine_update_remote_sshd () {


    #--[1] pushed using sshd connection
    if [[ $shhd_stat != true  ]]; then
        return
    fi


    #--[1.1] pushed using sshd connection
    cd $path_spin && git pull origin $repo_bran > /dev/null 2>&1 &&
    cd $path_spin && git push origin $repo_bran > /dev/null 2>&1 &&

    craine_prelo $? I59015 E59002
   
}


##--| push to remote host | http
function craine_update_remote_http () {


    #--[1] pushed using sshd connection
    if [[ $shhd_stat == true  ]]; then
        return
    fi
    
    if [[ $http_stat != true  ]]; then
        return
    fi


    #--[2.1] pushed using sshd connection
    cd $path_spin && git remote set-url origin "$repo_push"


    #--[2.2] pushed using sshd connection
    cd $path_spin && git pull origin $repo_bran > /dev/null 2>&1 &&
    cd $path_spin && git push origin $repo_bran > /dev/null 2>&1 &&
    craine_prelo $? I59015 E59002


    #--[2.3] pushed using sshd connection
    cd $path_spin && git remote set-url origin "$site_repo"  
}


##--| update to version tag repo
function craine_update_remote_tags () {
    

    if [[ $branc_msg == "2" ]]||[[ $branc_msg == "3" ]]||[[ $branc_msg == "4" ]];then
        return
    fi

    if [[ $option_mode != "minor" ]]&&[[ $option_mode != "major" ]]; then
        return
    fi


    #--[1] root file
    if [[ -z $sshd_stat  ]]&&[[ -z $http_stat ]];then
        return
    fi


    versions="$ver_major.$ver_minor.$ver_patch"


    #--[2] setup branch
    cd $path_spin && git tag -a "v$versions" -m "Release version $versions"


    #--[1] pushed using sshd connection
    if [[ $shhd_stat == true  ]]; then

        #--[1.1] pushed using sshd connection
        cd $path_spin && git pull origin "main" &&
        cd $path_spin && git push -u origin v$versions > /dev/null 2>&1 &&

        craine_prelo $? I59015 E59002


        #--[1.2] pushed using sshd connection
        return
    fi


    #--[2] pushed using http connection
    if [[ $http_stat == true  ]]; then

        #--[2.1] pushed using sshd connection
        cd $path_spin && git remote set-url origin "$repo_push"


        #--[2.2] pushed using sshd connection
        cd $path_spin && git pull origin "main" &&
        cd $path_spin && git push -u origin v$versions >  /dev/null 2>&1 &&
        craine_prelo $? I59015 E59002


        #--[2.3] pushed using sshd connection
        cd $path_spin && git remote set-url origin "$site_repo"
    fi
}


##--| update to latest tags repo
function craine_update_remote_late () {
    

    if [[ $branc_msg == "2" ]]||[[ $branc_msg == "3" ]]||[[ $branc_msg == "4" ]];then
        return
    fi

    if [[ $option_mode != "minor" ]]&&[[ $option_mode != "major" ]]; then
        return
    fi


    #--[1] root file
    if [[ -z $sshd_stat  ]]&&[[ -z $http_stat ]];then
        return
    fi


    #--[2] setup branch
    cd $path_spin && git tag -a "latest" -m "Latest Release version"


    #--[1] pushed using sshd connection
    if [[ $shhd_stat == true  ]]; then

        #--[1.1] pushed using sshd connection
        cd $path_spin && git pull origin "main" &&
        cd $path_spin && git push -u origin "latest" > /dev/null 2>&1 &&

        craine_prelo $? I59015 E59002


        #--[1.2] pushed using sshd connection
        return
    fi


    #--[2] pushed using http connection
    if [[ $http_stat == true  ]]; then

        #--[2.1] pushed using sshd connection
        cd $path_spin && git remote set-url origin "$repo_push"


        #--[2.2] pushed using sshd connection
        cd $path_spin && git push -u origin "latest" >  /dev/null 2>&1 &&
        craine_prelo $? I59015 E59002


        #--[2.3] pushed using sshd connection
        cd $path_spin && git remote set-url origin "$site_repo"
    fi
}




#######################################
##---| 3 PROGRESS
#######################################


##--| update main logic
function craine_update_remote () {


    #--[1] populate config file
    craine_update_datums_pool


    #--[2] adjusted config data
    craine_update_datums_proc

    
    #--[3] render welcome banner
    craine_banner_render_head


    #--[4] render option dialog
    craine_update_remote_dial


    #--[5] prepare version file
    craine_update_remote_prep


    #--[6] prepare branch data
    craine_update_remote_vers


    #--[7] validate preset keys
    craine_update_remote_keys


    #--[8] validate preset toke
    craine_update_remote_toke


    #--(9) checkout branch | alpha
    craine_update_remote_alpa


    #--(9) checkout branch | beta
    craine_update_remote_beta


    #--(9) checkout branch | devel
    craine_update_remote_devs


    #--(9) checkout branch | main
    craine_update_remote_main


    #--[10] check file changing 
    #craine_update_remote_null


    #--[11] defined commit texts
    craine_update_remote_pool


    #--[12] create release brach
    craine_update_remote_tags


    #--(13) update version | major
    craine_update_remote_majo


    #--(13) update version | minor
    craine_update_remote_mino


    #--(13) update version | pach
    craine_update_remote_bufi


    #--(14) push repository | sshd
    craine_update_remote_sshd


    #--(14) push repository | http
    craine_update_remote_http


    #--[15] update latest tags
    craine_update_remote_late


    #--[16] report process stat
    craine_report_status_info


    #--[10] purify data variable
    craine_update_datums_pure
}




#######################################
##--- PRESET
#######################################


function craine_update_preset () {
    craine_update_remote
}



#######################################
##--- PROSET
#######################################


function craine_update_proset() {
    craine_update_remote
}


#######################################
##--- PROTOS
#######################################


function craine_update_protos() {
    craine_update_remote
}



#######################################
##--- INITIAL
#######################################


function craine_update() {


    test -z $action_data && craine_update_notlog 4 1


    if [[ $action_data == "preset" ]]; then
        unset crain_data && craine_update_preset && exit 0
    fi


    if [[ $action_data == "proset" ]]; then
        unset crain_data && craine_update_proset && exit 0
    fi


    if [[ $action_data == "protos" ]]; then
        unset crain_data && craine_update_protos && exit 0
    fi


    if [[ $action_data == "release" ]]; then
        unset crain_data && craine_update_images && exit 0
    fi


    if [[ $action_data == "testing" ]]; then
        unset crain_data && craine_update_tester && exit 0
    fi
}