#!/bin/bash

set -e


if [[ -d "/var/lib/craine" ]];then
    approot="/var/lib/craine"
    appdirs="/var/lib/craine"

else
    approot="$(pwd)/library"
    appdirs="$(pwd)/library"
fi


## BOOTLOADERER
source "$appdirs/library/striper"



## ENVIRONTMENT
distro_releases=$2
distro_protocol=$4



if [[ $1 == "--dekstop" ]]; then
    craine_dekstop
elif [[ $1 == "--dialog" ]]; then
    craine_termine
else
    craine_hackers
fi