#!/bin/bash

set -e


setstatus="debug"

if [[ $setstatus != "debug" ]];then
    apppath="/var/lib/craine"
else
    apppath="$(pwd)"
fi


## BOOTLOADERER
disfile="$2"
applibs="$apppath/library"
source "$applibs/striper"


if [[ $1 == "--dekstop" ]]; then
    craine_dekstop
elif [[ $1 == "--dialog" ]]; then
    craine_termine
elif [[ $1 == "--devels" ]]; then
    craine_hackers --devels
elif [[ -e $1 ]]; then
    craine_hackers $1
else 
    echo "Craine Error: parameter is empty or config file not found"
fi