#!/bin/env bash
# autoload function

set -e



## SYSTEM

#-- craine core system structur
function craine_systems_struct() {

    system_assets="$craine_libs/assets"
    system_corest="$craine_libs/corest"
    system_config="$craine_libs/config"
    system_action="$craine_libs/proact"
    system_notefa="$craine_libs/notefa"
    
}


#-- craine core system configs
function craine_systems_config() {
    source "$system_config/system"
    source "$system_config/labrom"
}


#-- craine core system assets
function craine_systems_assets() {

    craine_banner="$system_assets/banner.txt"
    craine_brands="$system_assets/brands.png"
}



#-- craine core system actions
function craine_systems_corest() {
    
    source "$system_corest/assets"
    source "$system_corest/colors"
    source "$system_corest/config"
    source "$system_corest/parsed"
    source "$system_corest/remote"
    source "$system_corest/secure"
    source "$system_corest/deskto" 
}


#-- craine core system actions
function craine_systems_notefa() {
    
    source "$system_notefa/1000"
    source "$system_notefa/2000"
    source "$system_notefa/3000"
    source "$system_notefa/4000"
    source "$system_notefa/5000"
    source "$system_notefa/5100"
    source "$system_notefa/5200"
    source "$system_notefa/5300"
    source "$system_notefa/5400"
    source "$system_notefa/5500"
    source "$system_notefa/5600"
    source "$system_notefa/5700"
    source "$system_notefa/5800"
    source "$system_notefa/6000"
    source "$system_notefa/7000"
    source "$system_notefa/8000"
    source "$system_notefa/9000"
    source "$system_notefa/noog" 
}



function craine_systems_action() {

    source "$system_action/builds"
    source "$system_action/celine"
    source "$system_action/create"
    source "$system_action/delete"
    source "$system_action/geters"
    source "$system_action/modifi"
    source "$system_action/refane"
    source "$system_action/releas"
    source "$system_action/verser"

}



#-- craine core system initial
function craine_systems() {
    craine_systems_struct
    craine_systems_config
    craine_systems_notefa
    craine_systems_assets
    craine_systems_corest
    craine_systems_action
}




## MODULE

##-- load craine preset module and libary
function craine_modular_struct() {

    module_preset="$craine_libs/preset"
    module_proset="$craine_libs/proset"
    module_protos="$craine_libs/protos"
}


function craine_modular_preset() {

    # load library
    source "$module_preset/preset"
    source "$module_preset/parser"
} 


function craine_modular_proset() {
    source "$module_proset/proset"
}


function craine_modular_protos() {
    source "$module_protos/protos"
}


function craine_modular() {
    craine_modular_struct
    craine_modular_preset
    craine_modular_proset
    craine_modular_protos
}




## VENDOR

function craine_vendor_struct() {

    vendor_source="$craine_libs/vendor"
    vendor_editor="$vendor_source/editor"
}


function craine_vendor_prepar() {
    mkdir -p $vendor_source
}


function craine_vendor_editor() {

    local remote="https://github.com/lite-xl/lite-xl/releases/download/v2.1.8/lite-xl-v2.1.8-addons-linux-x86_64-portable.tar.gz"

    if [[ ! -f "$vendor_editor/lite-xl" ]];then
        curl -L -o /tmp/editor.tar.gz $remote &&  
        tar -xf /tmp/editor.tar.gz -C $craine_vendor &&
        mv -f $craine_vendor/lite-xl $vendor_editor
    fi

    vendor_editor="$vendor_editor/lite-xl"
    unset $remote
}
 

function craine_vendors() {
    craine_vendor_struct
    craine_vendor_prepar
    craine_vendor_editor
}




## WORKER 
function craine_workers_struct() {

    worker_folder="$HOME/.local/craine"
    worker_secret="$HOME/.ssh/crainkey"
    worker_preset="$worker_folder/preset"
    worker_protos="$worker_folder/protos"
    worker_proset="$worker_folder/proset"
    worker_prolab="$worker_folder/prolab"
    worker_preloc="$worker_folder/preloc"
    worker_config="$worker_folder/config"
    worker_logger="$worker_folder/logger"
    worker_tokens="$worker_folder/tokens"
}


function craine_workers_prepar() {
    
    mkdir -p $worker_folder
    mkdir -p $worker_secret
    mkdir -p $worker_preset
    mkdir -p $worker_proset
    mkdir -p $worker_prolab
    mkdir -p $worker_preloc
    mkdir -p $worker_config
    mkdir -p $worker_tokens
    mkdir -p $worker_logger
}


function craine_workers_preset() {

    local locals_source="$worker_preset/default"

    if [[ ! -d $locals_source ]];then
        craine_remote_clones "$remote_preset" "$locals_source"
    fi

    unset locals_source
}


function craine_workers_proset() {

    local locals_source="$worker_proset/default"

    if [[ ! -d $locals_source ]];then
        craine_remote_clones "$remote_proset" "$locals_source"
    fi

    unset locals_source
}


function craine_workers_protos() {

    local locals_source="$worker_protos/default"

    if [[ ! -d $locals_source ]];then
        craine_remote_clones "$remote_protos" "$locals_source"
    fi

    unset locals_source
}


function craine_workers_secret() {


    #--[1] create folder
    mkdir -p $worker_secret
    chmod -R 700 $worker_secret


    #--[2] create secret
    if [[ ! -f "$worker_secret/master"  ]];then
        ssh-keygen -q -t ed25519 -f $worker_secret/master -N ""
        chmod 600 $worker_secret/master
    fi
}


function craine_workers_tokens() {
    mkdir -p $worker_tokens/{preset,proset,protos} 
    chmod -R 700 $worker_tokens
}


function craine_workers_config() {
    cp -n $system_config/worker $worker_config
}


function craine_workers() {
    craine_workers_struct
    craine_workers_prepar
    craine_workers_preset
    craine_workers_proset
    craine_workers_protos
    craine_workers_secret
    craine_workers_tokens
    craine_workers_config
}



# LIBRARY LOAD
craine_systems
craine_vendors
craine_modular
craine_workers