#!/bin/env bash

set -e



#######################################
##--- 1 | HELPER
#######################################


# create ssh keys for module devel
function craine_create_helper_keysh() {
    echo "debug"
}


# prepare create report processing 
function craine_create_helper_report() {
    echo "debug"
}


# install default to target modules 
function craine_create_helper_clone() {
    echo "debug"
}




#######################################
##--- 2 | REMOTE
#######################################


# update master repo to late version
function craine_create_remote_latest() {

    local local_resource="$worker_folder/$action_data/default"

    cd $local_resource && git pull > /dev/null 2>&1

    if [[ $? -eq 0 ]]; then
        craine_create_notlog 1 1101
    else
        craine_create_notlog 3 1101
    fi
}


# create remote alpha stage branches
function craine_create_helper_altest() {
    echo "debug"
}


# create remote beta stages branches
function craine_create_helper_betest() {
    echo "debug"
}



#######################################
##--- 3 | VERSIO
#######################################


# generate commit message
function craine_create_versio_commit() {
    echo "debug"
}



#######################################
##--- DATUMS
#######################################


# 1 | command line base data organizer
function craine_create_enviro_preper() {


    ## logic variable
    option_spin=$( [[ -z $option_spin ]] && echo "default" || echo "$option_spin" )


    ## base variable
    base_name=$( craine_string_toname ${option_name} )
    base_slug=$( craine_string_toslug ${option_name} )
    base_lead=$( craine_string_tolead ${option_name} )
    base_vars=$( craine_string_tovars ${option_name} )
    


    ## spin variablbase_namee
    spin_name=$( craine_string_toname ${option_spin} )
    spin_slug=$( craine_string_toslug ${option_spin} )
    spin_lead=$( craine_string_tolead ${option_spin} )
    spin_vars=$( craine_string_tovars ${option_spin} )
    


    ## author variable
    auth_name=$( craine_string_toname "$option_auth" )    
    auth_lead=$( craine_string_toslug "$option_auth" )    
    auth_slug=$( craine_string_tolead "$option_auth" )    
    auth_vars=$( craine_string_tovars "$option_auth" ) 



    ## locals variable
    vars_rand=$( craine_string_random )
    path_base="$worker_folder/$action_data"
    path_main="$path_base/$base_slug"                                       # distros folders
    path_rand="$path_main/$vars_rand"                                       # temporary paths
    path_spin="$path_main/$spin_slug"                                       # variant folders



    ## remote variable
    repo_toke="$worker_folder/tokens/$action_data/$base_slug/$spin_slug"    # repository apts
    repo_host=$( craine_reposi_tohost $option_repo )                        # repository host
    repo_user=$( craine_reposi_touser $option_repo )                        # repository user
    repo_name=$( craine_reposi_torepo $option_repo )                        # repository name
    repo_http=$( craine_reposi_tohttp $option_repo )                        # repository link
    repo_sshd=$( craine_reposi_tosshd $option_repo )                        # repository name
    repo_push=$( craine_reposi_topush $option_repo )                        # repository push
    repo_keys="$worker_secret/master"                                       # repository sshd



    ## tokens variable
    toke_path="$repo_toke/repo"                                             # tokneizers path
    toke_data="$option_keys"                                                # tokneizers data
    


    ## notife variable
    stage_num=1
    alert_num=1
    erorr_num=1



    ##-- relative path replacement 
    ##   replace absolute home variable with tilda (~), fix perset creating function building 
    
    local worker_repdir="~/.local/craine"
    local worker_repsec="~/.ssh/crainkey/"

    rpat_base="$worker_repdir/$action_data"                                 # module directory
    rpat_main="$worker_repdir/$base_slug"                                   # distro directory
    rpat_spin="$worker_repdir/$vars_spin"                                   # varian directory
    rrep_keys="$worker_repsec/master"                                       # secret directory
    rrep_toke="$worker_repdir/tokens/$action_data/$base_slug/$vars_spin"    # tokens directory
}


# 2 | extract data to installs folder
function craine_create_enviro_instal() {
    echo "debug"
}


# 3 | save token data to secret vaults
function craine_create_datkeys() {
    echo debug
}


# 4 | save clean data to target folder
function craine_create_datload() {
    echo "debug"
}


# 5 | wipes temporer installation data
function craine_create_enviro_purify {
    
    ## distro variable
    unset envi_base
    unset envi_name
    unset envi_slug
    unset envi_auth

    ## locals variable 
    unset envi_link
    unset envi_locs
    unset envi_rand

    ## remote variable
    unset envi_repo
    unset envi_user
    unset envi_host
    unset envi_keys

    ## banner variable
    unset ban_prevs

    ## notife variable
    unset stage_num
    unset alert_num
    unset erorr_num
}



#######################################
##--- NOTLOG
#######################################


# (1) level info notif
function craine_create_notife_info() {


    ##--[1] declare varible for error code and text message
    local text=""
    local code="$1" 


    ##--[2] selection text message based on error code
    
    ##---(110) helper 
    test $code == 1101 && text="update default $action_data successfull" 
    

    ##---(120) preset
    test $code == 1201 && text="checking and prepare deployment target"
    test $code == 1202 && text="checking install sources availablility"
    test $code == 1203 && text="checking targets sources availablility"
    test $code == 1204 && text="creating targets sources workdirectory"
    test $code == 1205 && text="install modules to working directories"
    test $code == 1206 && text="create access tokens vault directories"
    test $code == 1207 && text="add personal access token to vaultfile"
    test $code == 1208 && text="writing user input data to tmp presets"
    test $code == 1209 && text="clone remote sources to working folder"
    test $code == 1210 && text="install preset to remote source folder"
    test $code == 1211 && text="purifiying source at temporary presets"


    ##---(130) proset
    test $code == 1301 && text="update default $action_data successfull"


    ##---(140) protos
    test $code == 1301 && text="update default $action_data successfull"



    ##--[3] render message
    test -n "$text" && craine_notif_stage "$text"
    

    ##--[4] clean variable
    unset code && unset text
}


# (1) level info loging 
function craine_create_logger_info() {
    echo debug > /dev/null
}


# (2) level warn notif 
function craine_create_notife_warn() {
    echo debug
}


# (2) level info loging
function craine_create_logger_warn() {
    echo debug
}


# (3) level error notif
function craine_create_notife_errs() {
    echo debug
}


# (3) level error loging
function craine_create_logger_errs() {
    echo debug
}


# (4) level fatal notif
function craine_create_notife_fail() {
    ##--[1] declare varible for error code and text message
    local text=""
    local code="$1" 


    ##--[2] selection text message based on error code
    
    ##---(410) helper 
    test $code == 4101 && text="update default $action_data successfull" 
    

    ##---(420) preset
    test $code == 4201 && text="conflicting name, $base_name $spin_name preset is existing"


    ##---(430) proset
    test $code == 4301 && text="update default $action_data successfull"


    ##---(440) protos
    test $code == 4301 && text="update default $action_data successfull"



    ##--[3] render message
    test -n "$text" && craine_notif_abort "$text" "$code"
    
    exit 0

    ##--[4] clean variable
    unset code && unset text
}


# (4) level fatal loging
function craine_create_logger_fail() {
    echo debug
}


# notife corest 
function craine_create_notlog() {

    local type="$1"
    local code="$2"

    if [[ $type == 1 ]];then
        craine_create_notife_info "$code"
        craine_create_logger_info "$code"
    fi

    if [[ $type == 2 ]];then
        craine_create_notife_warn "$code"
        craine_create_logger_warn "$code"
    fi

    if [[ $type == 3 ]];then
        craine_create_notife_errs "$code"
        craine_create_logger_errs "$code"
    fi

    if [[ $type == 4 ]];then
        craine_create_notife_fail "$code"
        craine_create_logger_fail "$code"
    fi
}




#######################################
##--- BUILDER
#######################################


# release corest
function craine_create_making() {
    echo "debug"
}

#######################################
##--- RELEASE
#######################################


# release corest
function craine_create_images() {
    echo "debug"
}




#######################################
##--- TESTER
#######################################


# tester corest
function craine_create_tester() {
    echo "debug"
}




#######################################
##--- PRESET
#######################################

#--| display starting message and load modulars
function craine_create_preset_booter () {


    #--[1] validate build preset
    test -d $path_spin && craine_create_notlog 4 4201


    #--[2] starting build preset
    craine_baner_prime
    echo -e  "\t${green}  PREPARE BUILD MODULE                                              ${reset}" | sed 's/^[[:space:]]*//'
    echo -e  "\t${green} -------------------------------------------------------------------${reset}" | sed 's/^[[:space:]]*//'
}


#--| clone default preset to temporer directory
function craine_create_preset_prepar () {

    local path_core="$path_base/default"


    #--[1] checks preset working directory
    test -d $path_rand && craine_create_notlog 1 1202


    #--[2] checks preset master directory
    test -d $path_core && craine_create_notlog 1 1203


    #--[3] create preset working directory
    mkdir -p $path_rand &&

    if [[ $? -eq 0 ]]; then
        craine_create_notlog 1 1204
    else
        craine_create_notlog 3 1204
    fi

    
    #--[4] clone default preset to workdir
    cp -fr $path_core/* $path_rand &&

    if [[ $? -eq 0 ]]; then
        craine_create_notlog 1 1205
    else
        craine_create_notlog 3 1205
    fi


    #--[5] create tokens pat access folders
    mkdir -p $repo_toke &&

    if [[ $? -eq 0 ]]; then
        craine_create_notlog 1 1206
    else
        craine_create_notlog 3 1206
    fi


    #--[6] write token data to vault folder
    echo "$toke_data" > "$toke_path" &&
    
    if [[ $? -eq 0 ]]; then
        craine_create_notlog 1 1207
    else
        craine_create_notlog 3 1207
    fi

    unset path_core
}


#--| write userinput to temporer direcotry envi
function craine_create_preset_writer () {

    craine_preset_parser_prenvi &&

    if [[ $? -eq 0 ]]; then
        craine_create_notlog 1 1208
    else
        craine_create_notlog 3 1204
    fi
}


#--| clone remote preset repository to workerdir
function craine_create_preset_remote () {

    craine_remote_clones $repo_http $path_spin &&
    
    if [[ $? -eq 0 ]]; then
        craine_create_notlog 1 1209
    else
        craine_create_notlog 3 1204
    fi
}


#--| write userinput to temporer direcotry envi
function craine_create_preset_instal () {


    #--[1] copy preset data from temporary folder

    cp -fr $path_rand/* $path_spin &&
    
    if [[ $? -eq 0 ]]; then
        craine_create_notlog 1 1210
    else
        craine_create_notlog 3 1204
    fi


    #--[2] remove temporary preset directories

    rm -fr $path_rand &&

    if [[ $? -eq 0 ]]; then
        craine_create_notlog 1 1211
    else
        craine_create_notlog 3 1204
    fi
}


#--| commited preset to their remote repository
function craine_create_preset_commit () {

    echo "first commit"
}


#--| confirmed user data using system previewer
function craine_create_preset_report () {


    craine_baner_prime

    echo -e  "\t${green}   PRESET OVERVIEW                                                  ${reset}" | sed 's/^[[:space:]]*//' 
    echo -e  "\t${green} -------------------------------------------------------------------${reset}" | sed 's/^[[:space:]]*//'
    echo -e  "\t${green}   distro   | $base_name                                            ${reset}" | sed 's/^[[:space:]]*//'
    echo -e  "\t${green}   author   | $auth_name                                            ${reset}" | sed 's/^[[:space:]]*//'
    echo -e  "\t${green}   variant  | $path_spin                                            ${reset}" | sed 's/^[[:space:]]*//'
    echo -e  "\t${green}   install  | $path_main                                            ${reset}" | sed 's/^[[:space:]]*//'
    echo -e  "\t${green} -------------------------------------------------------------------${reset}" | sed 's/^[[:space:]]*//'
    echo -e  "\t${green}   REMOTE REPOSITORY                                                ${reset}" | sed 's/^[[:space:]]*//'
    echo -e  "\t${green} -------------------------------------------------------------------${reset}" | sed 's/^[[:space:]]*//'
    echo -e  "\t${green}   host     | $repo_host                                            ${reset}" | sed 's/^[[:space:]]*//'
    echo -e  "\t${green}   user     | $repo_user                                            ${reset}" | sed 's/^[[:space:]]*//'
    echo -e  "\t${green}   repo     | $repo_name                                            ${reset}" | sed 's/^[[:space:]]*//'
    echo -e  "\t${green}   sshd     | $repo_sshd                                            ${reset}" | sed 's/^[[:space:]]*//'
    echo -e  "\t${green}   http     | $repo_http                                            ${reset}" | sed 's/^[[:space:]]*//'
    echo -e  "\t${green}   keys     | $repo_keys                                            ${reset}" | sed 's/^[[:space:]]*//'
    echo -e  "\t${green} -------------------------------------------------------------------${reset}" | sed 's/^[[:space:]]*//'
    echo -e  "\t${green}   BUILD INFORMATION                                                ${reset}" | sed 's/^[[:space:]]*//'
    echo -e  "\t${green} -------------------------------------------------------------------${reset}" | sed 's/^[[:space:]]*//'
    echo -e  "\t${green}   logpath  |                                                       ${reset}" | sed 's/^[[:space:]]*//'
    echo -e  "\t${green}   keypath  |                                                       ${reset}" | sed 's/^[[:space:]]*//'
    echo -e  "\t${green} -------------------------------------------------------------------${reset}" | sed 's/^[[:space:]]*//'
    echo -ne "\t${green}   Do you want create distro based on current preview data: [Y/n]   ${reset}" | sed 's/^[[:space:]]*//' && 
    
    read ban_prevs

    
    if [[ $ban_prevs == "Y" ]]||[[ $ban_prevs == "y" ]];then
        echo editing
    fi
    
    test -z  $aborted && exit 0
}


#--| edit preset working directory environtment
function craine_create_preset_editor () {
    craine_module_editor $path_rand/envi
}


#--| preset corest
function craine_create_preset() {

    #--[1] declare userinput data and setup for build 
    craine_create_enviro_preper


    #--[2] display starting message and load modulars 
    craine_create_preset_booter


    #--[3] download to latest version default presets
    craine_create_remote_latest


    #--[4] clone default preset to temporer directory 
    craine_create_preset_prepar


    #--[5] write userinput to temporer direcotry envi 
    craine_create_preset_writer


    #--[6] clone remote preset repository to workerdir 
    craine_create_preset_remote


    #--[7] clone temporer data to workdir and cleanup
    craine_create_preset_instal


    #--[8] commited preset to their remote repository
    #craine_create_preset_commit


    #--[10] display new preset final report parameter
    craine_create_preset_report


    #--[5] provide user edit on build wokerdir preset 
    #craine_create_preset_editor

    #--[11] purge build variable from current procces 
    craine_create_enviro_purify 


}




#######################################
##--- PROSET
#######################################


#--|  display new preset final report parameter
function craine_create_proset_report () {
    
    sleep 2 && craine_baner_prime
    echo -e  "\t${green} |  BUILD REPORTING                                                  ${reset}"
    echo -e  "\t${green} |-------------------------------------------------------------------${reset}"
    echo -e  "\t${green} |  base     | $option_name                                          ${reset}"
    echo -e  "\t${green} |  spin     | $option_spin                                          ${reset}"
    echo -e  "\t${green} |  error    |                                                       ${reset}"
    echo -e  "\t${green} |-------------------------------------------------------------------${reset}"
    echo -e  "\t${green} |  REMOTE REPOSITORY                                                ${reset}"
    echo -e  "\t${green} |-------------------------------------------------------------------${reset}"
    echo -e  "\t${green} |  user     |                                                       ${reset}"
    echo -e  "\t${green} |  host     |                                                       ${reset}"
    echo -e  "\t${green} |  base     |                                                       ${reset}"
    echo -e  "\t${green} |  repo     | $craine_link                                          ${reset}"
    echo -e  "\t${green} |  keys     | $craine_keys                                          ${reset}"
    echo -e  "\t${green} |-------------------------------------------------------------------${reset}"
}



# proset corest
function craine_create_proset() {
    echo "debug"
}




#######################################
##--- PROTOS
#######################################


# protos corest
function craine_create_protos() {
    echo "debug"
}




#######################################
##--- INITIAL
#######################################


# main process 
function craine_create() { 

    test -z $action_data && craine_create_notlog 4 1
    

    if [[ $action_data == "preset" ]]; then
        unset crain_data && craine_create_preset && exit 0
    fi

    if [[ $action_data == "proset" ]]; then
        unset crain_data && craine_create_proset && exit 0
    fi

    if [[ $action_data == "protos" ]]; then
        unset crain_data && craine_create_protos && exit 0
    fi

    if [[ $action_data == "release" ]]; then
        unset crain_data && craine_create_images && exit 0
    fi

    if [[ $action_data == "testing" ]]; then
        unset crain_data && craine_create_tester && exit 0
    fi
}
