#!/bin/env bash

set -e


## DISTRO PARSER
function craine_module_tovars() {
    
    local string=${1}
    local string=${string,,}                                  # string to lower
    local string=$( echo "${string}" | sed 's/ os//g' )       # remove os string
    local string=$( echo "${string}" | sed 's/ linux//g' )    # remove linux string
    local string=$( echo "${string}" | sed 's/ system//g' )   # remove system string
    local string="${string// /_}"                             # replace all spaces with underscore        
    local string="${string//-/_}"                             # replace all hyphens with underscore 
    echo ${string}
}


function craine_module_toslug() {
    
    local string=${1}
    local string=${string,,}                                  # string to lower
    local string=$( echo "${string}" | sed 's/ os//g' )       # remove os string
    local string=$( echo "${string}" | sed 's/ linux//g' )    # remove linux string
    local string=$( echo "${string}" | sed 's/ system//g' )   # remove system string
    local string="${string// /-}"                             # replace all spaces with hyphens        
    local string="${string//_/-}"                             # replace all underscore with hyphens
    echo ${string}
}


function craine_module_toname() {
    
    local string=${1}
    local string=$(echo "${string}" | sed -E 's/(^|\s+)([a-z])/\1\U\2/g')   # capitalize all first word
    local string="${string//-/ }"                                           # replace all hyphens with spaces         
    local string="${string//_/ }"                                           # replace all underscore with spaces
    echo ${string}
}


function craine_module_tolead() {
    
    local string=${1}
    local string="${string^^}"                                              # uppercase all character
    local string="${string//-/ }"                                           # replace all hyphens with spaces         
    local string="${string//_/ }"                                           # replace all underscore with spaces
    echo ${string}
}


## REPOSITORY PARSER


function craine_remote_torepo () {

    local parser=${1}

    if [[ -n $( echo ${parser} | grep "https://" ) ]];then
        local parser=$(basename ${parser} )
    else
        local parser=$( echo ${parser} | sed 's|.*/||' )
    fi

    echo "$parser"
    unset parser
}


function craine_remote_touser () {

    local parser=${1}

    if [[ -n $( echo ${parser} | grep "https://" ) ]];then
        local parser=$( basename "$(dirname "$parser")")
    else
        local parser=$( echo ${parser} | sed 's/.*:\([^/]*\)\/.*/\1/' )
    fi

    echo "$parser"
    unset parser
}


function craine_remote_tohost () {

    local parser=${1}

    if [[ -n $( echo ${parser} | grep "https://" ) ]];then
        local parser=$( echo ${parser} | cut -d/ -f3)
    else
        local parser=$( echo ${parser} | sed -E 's/.*@([^:]*):.*/\1/' )
    fi
    
    echo "$parser"
    unset parser
}


function craine_remote_topush () {

    local parser=${1} 
    local naming=$( craine_remote_torepo $parser )
    local userer=$( craine_remote_touser $parser )
    local hoster=$( craine_remote_tohost $parser )
    local parser="https://${userer}:${repo_keys}@${hoster}/${userer}/${naming}"

    echo "$parser"
    unset parser
    unset naming
    unset userer
    unset hoster
}


function craine_remote_tohttp () {
    
    local parser=${1}

    local naming=$( craine_remote_torepo $parser )
    local userer=$( craine_remote_touser $parser )
    local hoster=$( craine_remote_tohost $parser )
    local parser="https://${hoster}/${userer}/${naming}"
   
    echo "$parser"
    unset parser
}


function craine_remote_tosshd () {

    local parser=${1}

    local naming=$( craine_remote_torepo $parser )
    local userer=$( craine_remote_touser $parser )
    local hoster=$( craine_remote_tohost $parser )
    local parser="git@${hoster}:${userer}/${naming}"
   
    echo "$parser"
    unset parser
}






## REPLACE STRING

function craine_string_totime () {
    echo $(date "+%Y.%m.%d.%H.%M.%S")
}

function craine_string_torand () {
    local random_number=$(( ( RANDOM % 900000 ) + 100000 ))
    echo $random_number
    unset random_number
}



## REPLACE FILEBASE

#-- replace all string on file
function craine_string_replace () {

    local target="${1}"
    local replac="${2}"
    local filers="${3}"

    sed -i "s/$target/$replac/g" $filers

    unset target
    unset replac
    unset filers
}


#-- replace variable value base on key
function craine_varkey_rewrite () {

    local keyvar="${1}"
    local values='"'${2}'"'
    local config="${3}"

    if [[ $keyvar == "repo_sshd" ]]; then
        sed -i "s@^\(${keyvar}=\).*#\1${values}@" "$config"
    else
        sed -i "s@^\(${keyvar}=\).*@\1${values}@" "$config"
    fi
    
    unset keyvar
    unset values
    unset config
}




## STRING REPLACING

function craine_stringt_uncor() {

    local strep="${1// /_}"     # replace all spaces with underscore        
    local strep="${strep//-/_}" # replace all hypens with underscore
    echo ${strep,,}
}


function craine_stringt_strip() {

    local strep="${1// /-}"     # replace all spaces with hyphens        
    local strep="${strep//_/-}" # replace all underscore with hyphens
    
    echo ${strep,,}

}


function craine_string_allcap() {
    echo "$1" | sed -E 's/(^|\s+)([a-z])/\1\U\2/g'
}


function craine_string_pather() {

    local strep=${1,,}                                     # string to lower
    local strep=$( echo "${strep}" | sed 's/os//g' )       # remove os string
    local strep=$( echo "${strep}" | sed 's/linux//g' )    # remove linux string
    local strep=$( echo "${strep}" | sed 's/system//g' )   # remove system string
    local strep="${strep//-/}"                             # replace all spaces with hyphens        
    local strep="${strep//_/}"                             # replace all underscore with hyphens
    echo ${strep}
    
}


function craine_string_geturi() {
    echo "$1" | cut -d/ -f3
}

function craine_string_getlas() {
    basename "$1"
}

function craine_string_gettwo() {
    basename "$(dirname "$1")"
}




function craine_basename_path() {
    local dirname=$(basename $craine_link | sed 's/.git//g' )
    echo "$dirname"
}