#!/bin/env bash

## UPDATE OPERATION

#-- push operation major version
function craine_update_version() {
    echo "update"
}


#-- push operation minor version 
function craine_update_feature() {
    echo "update"
}


#-- push operation patch version
function craine_update_patcher() {
    echo "update"
}


#-- push operation withouts version
function craine_update_creater() {
    echo "update"
}


function craine_update() {
    echo debug
}