#!/bin/env bash
## craine update


#######################################
##--- DATUMS
#######################################

# 1 | command line base data organizer

function craine_update_datums_pooled () {
   

    ## logic variable
    option_spin=$( [[ -z $option_spin ]] && echo "default" || echo "$option_spin" )


    ## loads sources
    local base_conf="$worker_folder/$action_data/$option_name/$option_spin/crain"
    

    if [[ ! -f $base_conf ]];then

        echo "error : file not found" && exit 0
    else

        source $base_conf
    fi


    ## base variable
    base_name=$( craine_module_toname ${base_name} )
    base_slug=$( craine_module_toslug ${base_name} )
    base_lead=$( craine_module_tolead ${base_name} )
    base_vars=$( craine_module_tovars ${base_name} )
    


    ## spin variablbase_namee
    spin_name=$( craine_module_toname ${spin_name} )
    spin_slug=$( craine_module_toslug ${spin_name} )
    spin_lead=$( craine_module_tolead ${spin_name} )
    spin_vars=$( craine_module_tovars ${spin_name} )
    


    ## author variable
    auth_name=$( craine_module_toname "$auth_name" )    
    auth_lead=$( craine_module_toslug "$auth_name" )    
    auth_slug=$( craine_module_tolead "$auth_name" )    
    auth_vars=$( craine_module_tovars "$auth_name" ) 



    ## locals variable
    vars_rand=$( craine_module_filetim )
    path_base="$worker_folder/$action_data"
    path_main="$path_base/$base_slug"                                       # distros folders
    path_rand="$path_main/$vars_rand"                                       # temporary paths
    path_spin="$path_main/$spin_slug"                                       # variant folders
    


    ## remote variable
    repo_toke="$worker_folder/tokens/$action_data/$base_slug/$spin_slug"    # repository apts
    repo_host=$( craine_remote_tohost $base_repo )                          # repository host
    repo_user=$( craine_remote_touser $base_repo )                          # repository user
    repo_name=$( craine_remote_torepo $base_repo )                          # repository name
    repo_http=$( craine_remote_tohttp $base_repo )                          # repository link
    repo_sshd=$( craine_remote_tosshd $base_repo )                          # repository name
    repo_push=$( craine_remote_topush $base_repo )                          # repository push
    repo_keys="$worker_secret/master"                                       # repository sshd



    ## loging variable                                       
    logs_file="$worker_logger/$action_mode-$action_data-$vars_rand"         # logging filedat
    logs_pack="$path_spin/track/$vars_rand"
    logs_make="$path_spin/track/_init"



    ## tokens variable
    toke_path="$repo_toke/repo"                                             # tokneizers path
    toke_data=$( cat $toke_path )                                                # tokneizers data
    repo_keys="https://${repo_user}:${toke_data}@${repo_host}/${repo_user}/${repo_name}"


    ## notife variable
    stage_num=1
    alert_num=1
    erorr_num=1

}


#######################################
##--- PROGRES
#######################################

##--[1] validate secret
function craine_update_remote_secret () {


    #--[1] initialzer ssh-agents
    if [[ ! -f $worker_secret/master  ]];then    
        return
    fi


    #--[2] initialzer ssh-agents 
    eval "$(ssh-agent -s)" > /dev/null 2>&1 &&


    #--[3] add secret to ssh agent 
    ssh-add $worker_secret/master > /dev/null 2>&1


    #--[4] connection test to github
    yes | ssh -T git@github.com >  /dev/null 2>&1

    
    #--[5] validate ssh connection
    cd $path_spin && git ls-remote --exit-code $repo_sshd > /dev/null 2>&1
    

    #--[1] validate ssh connection
    if [[ $? -eq 0 ]]; then
        sshd_stat=true 
    fi
}


##--[2] validate tokens
function craine_update_remote_tokens () {


    #--[1] validate ssh connection, return false is ssh connection available
    if [[ $sshd_stat == true ]];then
        return
    fi


    #--[2] check personal access tokens available, exit with error code if not exist
    if [[ -z toke_data ]];then
        echo "no remote resources available" && exit 1
    fi


    #--[3] validate uri connection
    cd $path_spin && git remote set-url origin "$repo_keys"


    #--[4] validate uri connection
    test -z $http_keys && cd $path_spin &&  git ls-remote --exit-code $repo_http > /dev/null 2>&1


    #--[5] validate uri connection
    if [[ $? -ne 0 ]]; then

        #--[5-1] validate uri connection
        cd $path_spin && git remote set-url origin "$base_repo"

        #--[5-2] validate uri connection
        echo "no remote resources available" && exit 1
    fi


    #--[6] validate uri connection
    http_stat=true 


    #--[7] validate uri connection
    cd $path_spin && git remote set-url origin "$base_repo"
}



function craine_update_remote_commit () {

    #--[1] validate uri connection
    cd $path_spin && git add . &&


    #--[2] validate uri connection
    cd $path_spin && git commit -m "update version $ver_major.$ver_minor.$ver_patch at $(date '+%A %W %Y %X')"
}


function craine_update_remote_pushed () {

    #--[1] pushed using sshd connection
    if [[ $shhd_stat == true  ]]; then

        #--[1.1] pushed using sshd connection
        cd $path_spin && git push &&

        #--[1.2] pushed using sshd connection
        return
    fi


    #--[2] pushed using http connection
    if [[ $http_stat == true  ]]; then

        #--[2.1] pushed using sshd connection
        cd $path_spin && git remote set-url origin "$repo_keys"

        #--[2.2] pushed using sshd connection
        cd $path_spin && git push &&

        #--[2.3] pushed using sshd connection
        cd $path_spin && git remote set-url origin "$base_repo"
    fi   
}



#######################################
##--- VERSION
#######################################


function craine_update_versio_majors() {


    #--[1] root file
    if [[ -z $sshd_stat  ]]&&[[ -z $http_stat ]];then
        return
    fi


    #--[1] root file
    local envi_file="$path_spin/crain"


    #--[1] root file
    ver_major=$((ver_major + 1 ))


    #--[1] root file
    sed -i "s@^\(ver_major=\).*@\1${ver_major}@" "$envi_file"
}


function craine_update_versio_minors() {

    
    #--[1] root file
    if [[ -z $sshd_stat  ]]&&[[ -z $http_stat ]];then
        return
    fi


    #--[1] root file
    local envi_file="$path_spin/crain"


    #--[1] root file
    ver_minor=$((ver_minor + 1 ))


    #--[1] root file
    sed -i "s@^\(ver_minor=\).*@\1${ver_minor}@" "$envi_file"
}


function craine_update_versio_patchs() {


    #--[1] root file
    if [[ -z $sshd_stat  ]]&&[[ -z $http_stat ]];then
        return
    fi


    #--[1] root file
    local envi_file="$path_spin/crain"


    #--[1] root file
    ver_patch=$((ver_patch + 1 ))


    #--[1] root file
    sed -i "s@^\(ver_patch=\).*@\1${ver_patch}@" "$envi_file"
}



#######################################
##--- PRESET
#######################################


function craine_update_preset_majors() {

    #--[1] populate preset data
    craine_update_datums_pooled


    #--[2] validate preset keys
    craine_update_remote_secret


    #--[3] validate preset toke
    craine_update_remote_tokens


    #--[4] update patch numbers
    craine_update_versio_majors


    #--[5] defined commit texts
    craine_update_remote_commit


    #--[6] updates repositories
    craine_update_remote_pushed
}


function craine_update_preset_minors() {

    #--[1] populate preset data
    craine_update_datums_pooled


    #--[2] validate preset keys
    craine_update_remote_secret


    #--[3] validate preset toke
    craine_update_remote_tokens


    #--[4] update patch numbers
    craine_update_versio_minors


    #--[5] defined commit texts
    craine_update_remote_commit


    #--[6] updates repositories
    craine_update_remote_pushed
}


function craine_update_preset_patchs() {


    #--[1] populate preset data
    craine_update_datums_pooled


    #--[2] validate preset keys
    craine_update_remote_secret


    #--[3] validate preset toke
    craine_update_remote_tokens


    #--[4] update patch numbers
    craine_update_versio_patchs


    #--[5] defined commit texts
    craine_update_remote_commit


    #--[6] updates repositories
    craine_update_remote_pushed
}


function craine_update_preset() {

    if [[ $option_mode == "minor" ]]; then

        craine_update_preset_minors

    elif [[ $option_mode == "major" ]]; then

        craine_update_preset_majors

    else

        craine_update_preset_patchs
    fi
}



#######################################
##--- PROSET
#######################################


function craine_update_proset() {
    echo debug
}


#######################################
##--- PROTOS
#######################################


function craine_update_protos() {
    echo debug
}



#######################################
##--- INITIAL
#######################################


function craine_update() {


    test -z $action_data && craine_create_notlog 4 1


    if [[ $action_data == "preset" ]]; then
        unset crain_data && craine_update_preset && exit 0
    fi


    if [[ $action_data == "proset" ]]; then
        unset crain_data && craine_update_proset && exit 0
    fi


    if [[ $action_data == "protos" ]]; then
        unset crain_data && craine_update_protos && exit 0
    fi


    if [[ $action_data == "release" ]]; then
        unset crain_data && craine_update_images && exit 0
    fi


    if [[ $action_data == "testing" ]]; then
        unset crain_data && craine_update_tester && exit 0
    fi
}