#!/bin/env bash
# notification and logs generator
#
#--------------------------------
# Module Classification
# -------------------------------
#
#--[1] assets
#--[2] config
#   |--[21] colors
#--[3] corest
#   |--[31] assets
#   |--[32] booter
#--[4] preset
#   |--[41] parser
#   |--[41] preset
#--[5] proact
#   |--[51] builds
#   |--[52] celine
#   |--[53] create
#   |--[54] delete
#   |--[55] getter
#   |--[56] modifi
#   |--[57] refane
#   |--[58] releas
#   |--[59] verser
#--[6] prolab
#--[7] proset
#--[8] protoc
#--[9] protos 
#
#


set -e


#######################################
##---| 1  NOTIF
#######################################

function craine_notif_stage() {

    local temp=$1
    local text=${!temp}

    test -n "$1" && echo -e "\t${white}        |                                            ${reset}" | sed 's/^[[:space:]]*//'
    test -n "$1" && echo -e "\t${lightPurple} stage ${white}($stage_num)───> ${cyan}$text   ${reset}" | sed 's/^[[:space:]]*//'
    ((stage_num++)) 
}


function craine_notif_warns() {
    
    local temp=$1
    local text=${!temp}

    test -n "$1" && echo -e "\t${white}        |                                            ${reset}" | sed 's/^[[:space:]]*//'
    test -n "$1" && echo -e "\t${yellow} warns ${white}($stage_num)───> ${lightYellow}$text ${reset}" | sed 's/^[[:space:]]*//'
    ((alert_num++)) 
    ((stage_num++))
}


function craine_notif_error() {
    
    local temp=$1
    local text=${!temp}

    test -n "$1" && echo -e "\t${white}        |                                            ${reset}" | sed 's/^[[:space:]]*//'
    test -n "$1" && echo -e "\t${red} error ${white}($stage_num)───> ${Redled}$text         ${reset}" | sed 's/^[[:space:]]*//'
    ((alert_num++))
    ((stage_num++))
}


function craine_notif_abort() {

    local temp=$1
    local text=${!temp}

    #--[1] clean all data environtment
    craine_update_datum_pure


    #--[2] abort all process
    echo -e "\t${red}                                                                  "${reset} | sed 's/^[[:space:]]*//'
    echo -e "\t${red}┌────────────────────────────────────────────────────────────────┐"${reset} | sed 's/^[[:space:]]*//'
    echo -e "\t${red}|                                                                |"${reset} | sed 's/^[[:space:]]*//'
    echo -e "\t${red}│        / \                                                     │"${reset} | sed 's/^[[:space:]]*//'
    echo -e "\t${red}│       / | \     HELLO THERE !                                  │"${reset} | sed 's/^[[:space:]]*//'
    echo -e "\t${red}│      /  #  \    SOMETHING GOES WRONG,PROCESS TERMINATED        │"${reset} | sed 's/^[[:space:]]*//'
    echo -e "\t${red}│     /_______\                                                  │"${reset} | sed 's/^[[:space:]]*//'
    echo -e "\t${red}|                                                                |"${reset} | sed 's/^[[:space:]]*//' 
    echo -e "\t${red}└────────────────────────────────────────────────────────────────┘"${reset} | sed 's/^[[:space:]]*//'
    echo -e "\t${red}                                                                  "${reset} | sed 's/^[[:space:]]*//'    
    echo -e "\t${red} [$temp] ERROR                                                    "${reset} | sed 's/^[[:space:]]*//'
    echo -e "\t${red}   |                                                              "${reset} | sed 's/^[[:space:]]*//'
    echo -e "\t${red}   |─> $text                                                      "${reset} | sed 's/^[[:space:]]*//'
    echo -e "\t${red}                                                                  "${reset} | sed 's/^[[:space:]]*//'
    
    exit 1 
}




#######################################
##---| 2  LOGER
#######################################

function craine_loger_stage () {

    test -z $logs_core && return
    
    local code=$1
    local text=${!code}
    local time=$(date +"[%Y-%m-%d]-[%H:%M:%S]")

    echo -e "$time-($USER@$HOSTNAME)--| INFO - $code |--> $text" >> $logs_core
}


function craine_loger_warns () {

    test -z $logs_core && return

    local code=$1
    local text=${!code}
    local time=$(date +"[%Y-%m-%d]-[%H:%M:%S]")

    echo -e "$time-($USER@$HOSTNAME)--| WARN - $code |--> $text" >> $logs_core
}


function craine_loger_error () {

    test -z $logs_core && return

    local code=$1
    local text=${!code}
    local time=$(date +"[%Y-%m-%d]-[%H:%M:%S]")

    echo -e "$time-($USER@$HOSTNAME)--| EROR- $code |--> $text" >> $logs_core
}


function craine_loger_abort () {

    test -z $logs_core && return

    local code=$1
    local text=${!code}
    local time=$(date +"[%Y-%m-%d]-[%H:%M:%S]")

    echo -e "$time-($USER@$HOSTNAME)--| FAIL- $code |--> $text" >> $logs_core
}

# clone log to remote repo
function craine_loger_clone () {

    test -z $logs_core && return
    test -z $logs_pack && return

    cp -f $logs_core $logs_pack
}





#######################################
##---| 6  INITIAL
#######################################


function craine_nolog () {

    local code="$1"
    local type="${code:0:1}"
    

    if [[ $type == I ]];then
        craine_notif_stage $code
        craine_loger_stage $code
    fi

    if [[ $type == W ]];then
        craine_notif_warns $code
        craine_loger_warns $code
    fi

    if [[ $type == E ]];then
        craine_notif_error $code
        craine_loger_error $code
    fi

    if [[ $type == A ]];then
        craine_notif_abort $code
        craine_loger_abort $code
    fi
}


function craine_prelo () {

    local stat=$1
    local done=$2
    local fail=$2


    if [[ $stat -eq 0 ]]; then
        craine_nolog $done
    else
        craine_nolog $fail
    fi
}


